### ISSUE TITLE
Optional crop and fade in and/or out of samples

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#1]
Would be nice if the user wouldn't necessarily have to crop and fade their samples themselves. 
This also introduces the potential of using various bits of the same audio file, potentially randomised (by an external script depending on the user's application). 

E.g.

    <audioelement url="song1.wav" id="song-1" name="song-1" starttime="23" stoptime="67" fadein="1" fadeout="0.5"/>

for skipping the first 23 seconds of the fragment and everything after the 67th, and a one second fade in and .5 second fadeout. 

Also make part of the test creator, without making too crowded and distracting.

**Comment by nickjillings** [comment]
Like the idea, especially from a memory resource point of view by having one file chopped up into multiple fragments.

Any edits to the test schema are automatically included in the test creator, so the more attributes naturally creates more clutter.

In terms of creating this, it is not too difficult to achieve, especially the start/stop elements (there is now a buffer manipulator which copies the buffer to zero-pad for synchronous loops).

Should fadein/out be globally set as well as local (think of how the loudness attribute works) or should it only be `<audioelement>` specific, I could argue use cases both ways.

**Comment by BrechtDeMan** [comment]
Good question - I think a test-wide setting would suffice. 
Alternatively it could be test-wide, page-wide and audioelement-specific, with the more specific one taking precedence of course. But I can't think of a use case for it so this might be overcomplicating things (until someone asks for the feature)?

**Comment by nickjillings** [comment]
I was leaning to the last one myself, it's not really any more complicated (several other attributes behave this way) but the implementation either way is different.

**Comment by nickjillings** [comment]
startTime and stopTime are defined for `<audioelement>`. This does not currently work if synchronous=true for the page nor any checks that the numbers/times are valid.

Times are given in seconds as decimals

**Comment by nickjillings** [comment]
I think the cross-fade option does the same as fade-in/fade-out. Having multiple of these will require inserting more web audio nodes into the chain to handle separate gain ramps. If there is no cross-fade (ie it is the first played) it will still ramp from 0 to 1.

**Comment by BrechtDeMan** [comment]
Oh yes fair enough. I think I'd vote for simplicity here too. 

If you were to add fade in and fade out separately, you could have a fade out to complete silence before fading into the next sample, or you could have a fade out but then start full force, but that's getting very custom and probably not very useful. Anyone can do that themselves with a wave editor. So let's close? 

One question though: with the start and stop time, is the load on the connection and/or memory and/or CPU actually reduced, or would it be silly for me to upload full songs to the server and then add a start and stop time? If it would slow down the test I would not do it (for remote tests at least).

**Comment by nickjillings** [comment]
The core will always download the whole WAV file, it cannot pick out parts of a file to download. This is only useful if you have a song that you want to split up into chorus, verse 1, hook etc and show over multiple pages. In this case, the single file is downloaded and processed. Equally the loudness is taken for the 'whole' song not just the portion (unless we re-calculate for each portion).

In terms of memory, it shouldn't have any impact unless we have synchronous=true, where it will need to take a copy to zero-pad. That is the same case with any test state, it must always take a copy in-case the original is needed again later.

**Comment by nickjillings** [comment]
If however you have 10, 4 minute songs and you are only using the same 30s sample from each, better to cut them up.

**Comment by BrechtDeMan** [comment]
Gotcha, thanks.

**Comment by nickjillings** [comment]
Have not finished this yet!!

**Comment by BrechtDeMan** [comment]
Woops!
