### ISSUE TITLE
Reference/anchor required below/above certain value

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#103]
This is supposedly supported, from the documentation, but I can't find how to do it. 

It's quite sensible to expect the reference to be placed above a certain value, or the anchor below a certain value, before one can proceed (though in most cases this would be an after the fact selection of poor subjects). 

We can already enforce _a_ stimulus to be rated above or below a certain value (as in 'at least one'), but nothing else. 

Alternatively we can remove it from the documentation (for now at least) to avoid confusion. 

On a similar note, failed attempts to proceed should be logged (in time) as well.

**Comment by nickjillings** [comment]
You have to set the marker attribute.

From project.xml:
`<audioelement url="0.wav" gain="-6" id="track-5" type="anchor" marker="20"/>
<audioelement url="1.wav" gain="0.0" id="track-6" type="reference" marker="80"/>`

**Comment by BrechtDeMan** [comment]
Right, that's actually in the docs (though I may add an example in the wiki). My bad. 

Still has to be implemented in the test_create I believe, will add to #74. 

Have also created #105 as a separate issue.
