### ISSUE TITLE
Metrics: axis name issue

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#107]
If there are several axes with the same stimuli on one page, can we log which axis a certain 'check' (and more importantly: movement? I can't imagine this not being implemented so maybe it's a documentation/me issue).

**Comment by nickjillings** [comment]
All metrics are individually collected (hence all the hacky .prototype bits on the top of APE to over-rule the default behavior).

In terms of checks, in theory it should be possible to say only do a movement check on one axis and not the other (not sure if this is already in).

**Comment by BrechtDeMan** [comment]
So the movement is actually checked, but the attribute says `interface-name="null"`. 

I've made this with test_create, but I don't know where I would have had to enter the name. I have entered an interface name ('height' and 'depth') as title of the 'interface' and they show correctly above the axes, and I'm also reminded to 'move sliders 1 and 2 on axis "height"', for instance. 

There are currently no logs of 'check' events in the XML (see #105). 

I think this issue should probably be named differently. 

Configuration XML (using test_create): 
`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="APE"><exitText>Thank you.</exitText><survey location="pre"></survey><survey location="post"></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"><interfaceoption type="check" name="fragmentMoved"></interfaceoption><interfaceoption type="check" name="fragmentPlayed"></interfaceoption><interfaceoption type="check" name="fragmentComments"></interfaceoption><interfaceoption type="check" name="scalerange"></interfaceoption><interfaceoption type="show" name="comments"></interfaceoption><interfaceoption type="show" name="page-count"></interfaceoption></interface></setup><page id="testpage" hostURL="media/example/" randomiseOrder="true" repeatCount="0"><commentboxprefix>Describe fragment</commentboxprefix><interface name="null"><title>depth</title><scales><scalelabel position="0">a lot of text so it might fall of the screen but maybe not</scalelabel></scales></interface><interface name="null"><title>height</title></interface><audioelement id="one" url="1.wav" gain="0"></audioelement><audioelement id="two" url="2.wav" gain="0"></audioelement><survey location="pre"></survey><survey location="post"></survey></page></waet>`

Result XML: 
`<waetresult key="jeb66l7a6f1qfofyjs1m2uitbakqe8qw" state="update"><waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="test-schema.xsd" file-name="tests/multiaxis.xml" url="http://localhost:8000/tests/multiaxis.xml"><setup interface="APE"><exitText>Thank you.</exitText><survey location="pre"></survey><survey location="post"></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"><interfaceoption type="check" name="fragmentMoved"></interfaceoption><interfaceoption type="check" name="fragmentPlayed"></interfaceoption><interfaceoption type="check" name="fragmentComments"></interfaceoption><interfaceoption type="check" name="scalerange"></interfaceoption><interfaceoption type="show" name="comments"></interfaceoption><interfaceoption type="show" name="page-count"></interfaceoption></interface></setup><page id="testpage" hostURL="media/example/" randomiseOrder="true" repeatCount="0"><commentboxprefix>Describe fragment</commentboxprefix><interface name="null"><title>depth</title><scales><scalelabel position="0">a lot of text so it might fall of the screen but maybe not</scalelabel></scales></interface><interface name="null"><title>height</title></interface><audioelement id="one" url="1.wav" gain="0"></audioelement><audioelement id="two" url="2.wav" gain="0"></audioelement><survey location="pre"></survey><survey location="post"></survey></page></waet><datetime><date year="2016" month="5" day="27"></date><time hour="18" minute="24" secs="5"></time></datetime><navigator><platform>MacIntel</platform><vendor>Apple Computer, Inc.</vendor><uagent>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10</uagent><window innerWidth="1152" innerHeight="699"></window></navigator><survey location="pre" state="empty"></survey><survey location="post" state="empty"></survey><page ref="testpage" presentedId="0" state="complete"><survey location="pre" state="empty"></survey><survey location="post" state="empty"></survey><metric><metricresult id="testTime">20.20136054421755</metricresult></metric><audioelement ref="one" type="normal" url="1.wav" fqurl="http://localhost:8000/1.wav" gain="0" presentedId="1" playGain="0"><metric><metricresult name="enableElementTimer">2.072380952380854</metricresult><metricresult name="elementTrackerFull"><movement time="0" value="0.6332046332046332"></movement><movement time="16.09723356009067" value="0.46814671814671815"></movement><movement time="18.448253968253766" value="0.2519305019305019"></movement></metricresult><metricresult name="elementListenTracker"><event><testtime start="0" stop="0.9258956916098668"></testtime><buffertime start="0" stop="0.08124716504084972"></buffertime></event><event><testtime start="19.054875283446563" stop="20.20136054421755"></testtime><buffertime start="0" stop="0.30473922853298063"></buffertime></event></metricresult><metricresult name="elementInitialPosition">0.6332046332046332</metricresult><metricresult name="elementFlagListenedTo">true</metricresult><metricresult name="elementFlagMoved">true</metricresult><metricresult name="elementTrackerFull" interface-name="null" interface-id="0"><movement time="0" value="0.6332046332046332"></movement><movement time="16.09723356009067" value="0.46814671814671815"></movement></metricresult><metricresult name="elementInitialPosition" interface-name="null" interface-id="0">0.6332046332046332</metricresult><metricresult name="elementFlagMoved" interface-name="null" interface-id="0">true</metricresult><metricresult name="elementTrackerFull" interface-name="null" interface-id="1"><movement time="0" value="0.11003861003861004"></movement><movement time="18.448253968253766" value="0.2519305019305019"></movement></metricresult><metricresult name="elementInitialPosition" interface-name="null" interface-id="1">0.11003861003861004</metricresult><metricresult name="elementFlagMoved" interface-name="null" interface-id="1">true</metricresult></metric><file sampleRate="44100" channels="1" sampleCount="37121" duration="0.8417460322380066"></file><value interface-name="null">0.46814671814671815</value><value interface-name="null">0.2519305019305019</value><comment><question>Describe fragment 1</question><response></response></comment></audioelement><audioelement ref="two" type="normal" url="2.wav" fqurl="http://localhost:8000/2.wav" gain="0" presentedId="2" playGain="0"><metric><metricresult name="enableElementTimer">18.126077097505686</metricresult><metricresult name="elementTrackerFull"><movement time="0" value="0.693050193050193"></movement><movement time="3.082448979591618" value="0.8841698841698842"></movement><movement time="17.153741496598514" value="0.7953667953667953"></movement></metricresult><metricresult name="elementListenTracker"><event><testtime start="0.9287981859408774" stop="19.054875283446563"></testtime><buffertime start="0" stop="0.0012463746968478517"></buffertime></event></metricresult><metricresult name="elementInitialPosition">0.693050193050193</metricresult><metricresult name="elementFlagListenedTo">true</metricresult><metricresult name="elementFlagMoved">true</metricresult><metricresult name="elementTrackerFull" interface-name="null" interface-id="0"><movement time="0" value="0.693050193050193"></movement><movement time="17.153741496598514" value="0.7953667953667953"></movement></metricresult><metricresult name="elementInitialPosition" interface-name="null" interface-id="0">0.693050193050193</metricresult><metricresult name="elementFlagMoved" interface-name="null" interface-id="0">true</metricresult><metricresult name="elementTrackerFull" interface-name="null" interface-id="1"><movement time="0" value="0.5974903474903475"></movement><movement time="3.082448979591618" value="0.8841698841698842"></movement></metricresult><metricresult name="elementInitialPosition" interface-name="null" interface-id="1">0.5974903474903475</metricresult><metricresult name="elementFlagMoved" interface-name="null" interface-id="1">true</metricresult></metric><file sampleRate="44100" channels="1" sampleCount="53287" duration="1.2083220481872559"></file><value interface-name="null">0.7953667953667953</value><value interface-name="null">0.8841698841698842</value><comment><question>Describe fragment 2</question><response></response></comment></audioelement><error time="5.66566893424033">You have not moved the following sliders. On axis "depth" you must move sliders 1, 2. On axis "height" you must move slider 1. </error></page></waetresult>`

**Comment by nickjillings** [comment]
Both the interface-name attributes have a name of "null" in the configuration

**Comment by BrechtDeMan** [comment]
Indeed but that's the problem: why is this the case, how can I avoid this with test_create?
Or if my suspicion is correct, an 'interface-name' attribute should be added to test_create.

**Comment by nickjillings** [comment]
Need to add the interface-name attribute to test_create

**Comment by nickjillings** [comment]
Fixed in Dev_main (d955beb). Can now modify the interface-name attribute
