### ISSUE TITLE
Enter in survey triggers 'Next' twice

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#111]
As of recently, hitting enter once in a survey submits twice, so that you get the 'This question is mandatory' error for the next question, or skip it entirely if it's a non-mandatory question (dangerous!). (As in #83, hitting enter then only duplicates the lightbox.)

Possibly related to #64. 

See http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/test.html?url=salford.xml

**Comment by BrechtDeMan** [comment]
Actually, regarding #83, when you hit enter once, TWO more of these appear, so enter really does trigger the 'in-focus' button twice.

**Comment by nickjillings** [comment]
Same as #112, I cannot replicate this at all

**Comment by BrechtDeMan** [comment]
Not even in the example above? 
Also my comment boxes seem to have disappeared overnight. What is happening!

**Comment by nickjillings** [comment]
Strange, I am getting it there. That is not a recent commit. The core.js is old, none of the new loader.js or timers for loading the scripts.

Can you update to the latest master and try again?

**Comment by BrechtDeMan** [comment]
Latest master, emptied caches: http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/test.html?url=dalarna.xml

Can you confirm this is again not working for you? 

- No comment fields (`<interfaceoption type="show" name="comments"/>`?)
- This is an XML with just two pages, no poolSize specified, and yet the page count is 8! (#112)
- Enter skips two surveys at once - post-page this will trigger a warning as the second question is also mandatory.

`<?xml version="1.0" encoding="utf-8"?>
<waet
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="APE" projectReturn="save.php" randomiseOrder='true'>
        <survey location="before">
            <surveyentry type="statement" id="intro">
                <statement>
                    Thank you for choosing to participate in this experiment.
                </statement>
            </surveyentry>
        </survey>
        <survey location="after">
            <surveyentry type="statement" id="thankYou">
                <statement>Thank you for taking the test. Please take some time to answer the following survey questions</statement>
            </surveyentry>
            <surveyentry type="question" id="location" mandatory="true">
                <statement>Please enter your listening location (room identifier).</statement>
            </surveyentry>
            <surveyentry type="radio" id="gender" mandatory="true">
                <statement>Gender</statement>
                <option name="male">Male</option>
                <option name="female">Female</option>
                <option name="other">Other</option>
                <option name="preferNotToSay">Prefer not to say</option>
            </surveyentry>
            <surveyentry type="number" id="age" min="0">
                <statement>What is your age?</statement>
            </surveyentry>
            <surveyentry type="question" id="nativeLanguage" mandatory="true">
                <statement>What is your native language?</statement>
            </surveyentry>
            <surveyentry type="question" id="yearsAudio" mandatory="true">
                <statement>Number of years of experience in audio engineering:</statement>
            </surveyentry>
            <surveyentry type="question" id="experienceAudio" mandatory="true" boxsize="huge">
                <statement>Please specify your experience: What types of audio engineering, for how long, what level, what environment, paid/unpaid, part time/full time, which musical genres and instrumentation do/did you most often work on, ...</statement>
            </surveyentry>
            <surveyentry type="question" id="yearsInstr" mandatory="true">
                <statement>Number of years playing an instrument:</statement>
            </surveyentry>
            <surveyentry type="question" id="experienceInstr" mandatory="true" boxsize="huge">
                <statement>Please specify your experience: Which instruments, for how long, what level, what environment, paid/unpaid, part time/full time, which musical genres and band formations do/did you usually play in, ...</statement>
            </surveyentry>
            <surveyentry type="question" id="genrePref" mandatory="true">
                <statement>Which are your favourite musical genres to listen to?</statement>
            </surveyentry>
            <surveyentry type="radio" id="experienceListeningTests" mandatory="true">
                <statement>Have you participated in listening tests before? (Not including medical/clinical auditory exams.) If so, please specify.</statement>
                <option name="none">None</option>
                <option name="1-5">Between 1 and 5</option>
                <option name="5+">More than 5</option>
            </surveyentry>
            <surveyentry type="question" id="cold">
                <statement>Do you currently have a cold or other disease or condition which might affect your hearing?</statement>
            </surveyentry>
            <surveyentry type="question" id="generalExperience" boxsize="huge">
                <statement>Please describe your experience taking this test: was it generally easy/hard/boring/enjoyable? Do you have any further feedback?</statement>
            </surveyentry>
            <surveyentry type="question" id="interfaceExperience" boxsize="huge">
                <statement>(Last question!) Please describe your thoughts on the test design and interface: was it easy/difficult/annoying/fun to use? What do you think could be improved? Do you have any further feedback?</statement>
            </surveyentry>
            <surveyentry type="statement" id="thankYouEnd">
                <statement>Thank you for taking this listening test. Please click 'Submit' - only then your test results and survey responses will be recorded! </statement>
            </surveyentry>
        </survey>
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementInitialPosition</metricenable>
            <metricenable>elementTracker</metricenable>
            <metricenable>elementFlagListenedTo</metricenable>
            <metricenable>elementFlagMoved</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentComments"/>
            <interfaceoption type="check" name="fragmentPlayed"/>
            <interfaceoption type="show" name="page-count"/>
            <interfaceoption type="show" name="comments"/>
        </interface>
    </setup>
    <page id="InTheMeantime" hostURL="test-data/Dalarna/InTheMeantime/" randomiseOrder='true' repeatCount='0' loop='true' synchronous='true'>
        <commentboxprefix>Comment on fragment</commentboxprefix>
        <interface name="preference">
            <title>"PREFERENCE"</title>
            <scales>
                <scalelabel position="10">Bad</scalelabel>
                <scalelabel position="30">Poor</scalelabel>
                <scalelabel position="50">Fair</scalelabel>
                <scalelabel position="70">Good</scalelabel>
                <scalelabel position="90">Excellent</scalelabel>
            </scales>
        </interface>
        <audioelement url="DUA-A_-23LUFS.wav" name="DUA-A" id="DUA-A"/>
        <audioelement url="DUA-B_-23LUFS.wav" name="DUA-B" id="DUA-B"/>
        <audioelement url="DUA-C_-23LUFS.wav" name="DUA-C" id="DUA-C"/>
        <audioelement url="DUA-D_-23LUFS.wav" name="DUA-D" id="DUA-D"/>
        <audioelement url="DUA-E_-23LUFS.wav" name="DUA-E" id="DUA-E"/>
        <audioelement url="DUA-F_-23LUFS.wav" name="DUA-F" id="DUA-F"/>
        <commentquestion name="general" type="question">
            <statement>General comments</statement>
        </commentquestion>
        <survey location="before">
            <surveyentry type="statement" id="introPageInTheMeantime">
                <statement>Please take your time to carefully compare the different mixes.
                Click the different markers to play and toggle between the associated audio, and click 'Stop' to interrupt playback and rewind to the start of the fragments.
                Click once to play, drag to rate, and comment on the mixes in the corresponding numbered text boxes.
                When you are ready, please click 'Submit' to finish.</statement>
            </surveyentry>
        </survey>
        <survey location="after">
            <surveyentry type="question" id="songGenreInTheMeantime" name="songGenre" mandatory="true">
                <statement>How would you describe the genre of this song? Multiple answers possible. </statement>
            </surveyentry>
            <surveyentry type="question" id="songExperienceInTheMeantime" name="songExperience" mandatory="true" boxsize="large">
                <statement>Describe your experience with this task. Was it hard/easy? Were the mixes very similar/wildly different/somewhere in between? </statement>
            </surveyentry>
        </survey>
    </page>
    <page id="LeadMe" hostURL="test-data/Dalarna/LeadMe/" randomiseOrder='true' repeatCount='0' loop='true' synchronous='true'>
        <commentboxprefix>Comment on fragment</commentboxprefix>
        <interface name="preference">
            <title>"PREFERENCE"</title>
            <scales>
                <scalelabel position="10">Bad</scalelabel>
                <scalelabel position="30">Poor</scalelabel>
                <scalelabel position="50">Fair</scalelabel>
                <scalelabel position="70">Good</scalelabel>
                <scalelabel position="90">Excellent</scalelabel>
            </scales>
        </interface>
        <audioelement url="DUB-A_-23LUFS.wav" name="DUB-A" id="DUB-A"/>
        <audioelement url="DUB-B_-23LUFS.wav" name="DUB-B" id="DUB-B"/>
        <audioelement url="DUB-C_-23LUFS.wav" name="DUB-C" id="DUB-C"/>
        <audioelement url="DUB-D_-23LUFS.wav" name="DUB-D" id="DUB-D"/>
        <audioelement url="DUB-E_-23LUFS.wav" name="DUB-E" id="DUB-E"/>
        <audioelement url="DUB-F_-23LUFS.wav" name="DUB-F" id="DUB-F"/>
        <commentquestion name="general" type="question">
            <statement>General comments</statement>
        </commentquestion>
        <survey location="before">
            <surveyentry type="statement" id="introPageLeadMe">
                <statement>Please take your time to carefully compare the different mixes.
                Click the different markers to play and toggle between the associated audio, and click 'Stop' to interrupt playback and rewind to the start of the fragments.
                Click once to play, drag to rate, and comment on the mixes in the corresponding numbered text boxes.
                When you are ready, please click 'Submit' to finish.</statement>
            </surveyentry>
        </survey>
        <survey location="after">
            <surveyentry type="question" id="songGenreLeadMe" name="songGenre" mandatory="true">
                <statement>How would you describe the genre of this song? Multiple answers possible. </statement>
            </surveyentry>
            <surveyentry type="question" id="songExperienceLeadMe" name="songExperience" mandatory="true" boxsize="large">
                <statement>Describe your experience with this task. Was it hard/easy? Were the mixes very similar/wildly different/somewhere in between? </statement>
            </surveyentry>
        </survey>
    </page>
</waet>`

**Comment by nickjillings** [comment]
Your index.html and test.html are old. core.js is being loaded and run twice! Hence enter keys are bound twice causing the bug. The same for #112 as the page filtering is being called twice, picking out two sets of 4 pages.

Can you update the entire repository. Doing an scp from a clean copy of the repository will only update the WAET files, your salford.xml and media should be left untouched

**Comment by BrechtDeMan** [comment]
Ah of course. I'll start using rsync ([not a big fan of scp](http://stackoverflow.com/questions/20625000/scp-stalled-while-copying-large-files/35022779#35022779)), it's just a pain because it's so slow and you have to mount it first (no way to SSH into webprojects I think). 

The missing comment box problem persists though; opening another issue.
