### ISSUE TITLE
Twice as many pages as indicated

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#112]
Like #58, the pool is double the desired size, no repeatCount anywhere (and duplicates are present, see #59) since the last couple of commits (master). 

Was fine with 20 May commit, broken at some point over 26 and 27 May.

**Comment by nickjillings** [comment]
I can't replicate this bug in either Windows or OSX browsers. Are you positive it is an error? Does this happen with the example tests?

**Comment by BrechtDeMan** [comment]
I have since reverted to the 20 May state of things so my online test doesn't demonstrate my issue anymore. I have confirmed in both Chrome and Safari that I was getting 8 pages when I requested 4, and going back to an early commit (not just to the last master branch but sometime before the 26/27 commits) seems the way to solve it for now.

**Comment by nickjillings** [comment]
Do you know which commit broke it on the master branch?

**Comment by nickjillings** [comment]
The most recent time I've touched that part of the code was in commit abf3de886b80. Can you confirm if the commit directly before this one was broken or not? And then if this one broke it.

**Comment by BrechtDeMan** [comment]
Fixed, see #111
