### ISSUE TITLE
test_create: 'Edit scale markers' broken

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#115]
On the newest commit (and likely quite a few before that but have only properly tested it now), the 'Edit scale markers' pop up window is broken. You get this popup but selecting anything from the drop down menu doesn't make anything appear. 

'Add marker' still works so you can still make your axis complete with labels, you just can't access the presets. 

<img width="787" alt="screen shot 2016-05-31 at 18 46 12" src="https://cloud.githubusercontent.com/assets/4103243/15682884/f9b12dfe-275f-11e6-82d2-e7b5d6b6e868.png">

**Comment by nickjillings** [comment]
Fixed in  64ccaad
