### ISSUE TITLE
Master volume slider sticky

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#116]
Weird bug in latest commit: I want to drag the volume slider, and it is impossible to 'drop', it keeps on moving wherever I go on the screen. 
Clicking elsewhere doesn't work, I can't click any buttons or markers either. 

Both Safari and Chrome.

**Comment by nickjillings** [comment]
Should be fixed now with #95. Couldn't triage but all of the drag captured is better implemented now
