### ISSUE TITLE
Audioelements appear in reverse order

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#117]
With the following configuration, the audio samples appear in this order: 4, 3, 2, 1, 0

(Only an 'issue' in non-random mode, which is rare)

`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="MUSHRA" calibration="false"><exitText>Thank you.</exitText><survey location="pre"></survey><survey location="post"></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"><interfaceoption type="show" name="volume"></interfaceoption></interface></setup><page id="nonrandom" hostURL="media/example/" loudness="-23"><commentboxprefix>Comment on track</commentboxprefix><interface name="null"><title>Non-random</title><scales><scalelabel position="90">Excellent</scalelabel><scalelabel position="70">Good</scalelabel><scalelabel position="50">Fair</scalelabel><scalelabel position="30">Poor</scalelabel><scalelabel position="10">Bad</scalelabel></scales></interface><audioelement id="zero" url="0.wav" gain="0" type="reference"></audioelement><audioelement id="one" url="1.wav" gain="0"></audioelement><audioelement id="two" url="2.wav" gain="0"></audioelement><audioelement id="three" url="3.wav" gain="0" type="anchor"></audioelement><audioelement id="four" url="4.wav" gain="0"></audioelement><survey location="pre"></survey><survey location="post"></survey></page></waet>`

**Comment by nickjillings** [comment]
Fixed
