### ISSUE TITLE
Sort function after rating

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#119]
From [AES140 Workshop](http://www.aes.org/events/140/workshops/?ID=4896), by panel member Jan Berg. 

For MUSHRA-style interfaces, clicking the optional 'Sort' button moves around sliders such that they are in the order which the participant rated them in. Allows easy 'side by side' comparison of samples that are closest to each other in terms of the attribute being rated. 

Related to #118

**Comment by nickjillings** [comment]
This should be a very simple thing to implement in JavaScript. What we need is a way to have this in the schema. Perhaps `<interfaceoption type="show" name="fragmentSort" />`. That way it's simpler to implement and it is then up to the individual interface types to accept / ignore.

**Comment by BrechtDeMan** [comment]
Would be very cool to demo this in the second edition of the aforementioned workshop, four weeks from now 😁 

Could work for 
* MUSHRA
* Horizontal
* Discrete

**Comment by nickjillings** [comment]
All the suitable interfaces now have a sort button option. Enable it by using the following in the `<interface>` node:
```xml
<interfaceoption type="show" name="fragmentSort" />
```
