### ISSUE TITLE
APE Cannot drag loaded samples

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#122]
On iPhone 5, iOS 8.2

As in #121, I haven't experienced all markers turning green, but those that do cannot be dragged. The grey ones can be dragged without issue.

**Comment by nickjillings** [comment]
This seems now to be fixed. Will probably need to make the APE sliders themselves wider to improve the experience. 

Will also need to fully test the 'desktop' version to ensure both play nice. Pretty sure I haven't 'touched' anything with the mouse event orders, but you never know!

So consider APE on Dev_main WIP for now
