### ISSUE TITLE
Page Title does not display for AB, ABX or likert tests

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#128]
When using the title tag within a page, the tag does not display - the title remains 'Listening Test' The title tag does work within interface - but not the page title.

The interface titles (subtitles) seem to work ok, but not the main titles.

**Comment by nickjillings** [comment]
This should be fixed now because of another bug which caused the first interface title element to be copied into the page title. Now the correct title elements are used.
