### ISSUE TITLE
Separate Synchronous playback and looping

### ISSUE THREAD

**Issue by nickjillings** [BrechtDeMan/WebAudioEvaluationTool#13]

**Comment by BrechtDeMan** [comment]
This should now be an option in test_create, no? And documented as well.

**Comment by BrechtDeMan** [comment]
Allow synchronous="true" loop="false"

**Comment by nickjillings** [comment]
Pulling this out of v 1.2 as it is an enhancement on the feature but doesn't break any off-the-shelf natures.

**Comment by BrechtDeMan** [comment]
Not sure why this is still open, perhaps related to #147 ?

**Comment by nickjillings** [comment]
Urgent due to reference in #147.
