### ISSUE TITLE
Custom Error Messages

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#133]
Can we set up custom error messages for `<interfaceoption>` tags

Some error messages make no sense - like when forcing someone to make a choice within an AB or Likert test.

it would also be nice to customise the error message for users in all cases - we might not want to tell someone that 

> one track needs to be above 75% - but

 instead ask users to 

> use the full scale

**Comment by nickjillings** [comment]
Users can now specify an error message on a check by adding the following node in their XML:

```xml
    <interfaceoption type="check" name="scalerange" min="25" max="75">
        <errormessage>Test Error Message</errormessage>
    </interfaceoption>
```

If no node is given here then the default message set by the interface / core will be displayed. The default message will still be shown in the console and in the results XML allowing for easy determination of what issues occurred.
