### ISSUE TITLE
New: Survey Entry Object - Video

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#134]
Can we allow a new survey entry item to allow the paying of a video within a popup box?

Either we could host the video locally and load, or forward from youtube? either way?

Could have options return as to whether the video was played? maybe duration between video loading and next being clicked? (eg. time on surveyentry) could be a useful indication? Or no return like a statement box.

**Comment by djmoffat** [comment]
Hey, have we managed to make any progress on this?
I would really like to include it in a listening test that I was looking to run this week.

**Comment by nickjillings** [comment]
I will move on this tomorrow morning. Do you need a youtube link or a self-hosted?

**Comment by djmoffat** [comment]
Either would be fine. But I currently have it as a YouTube link

---
Dave Moffat
Phone: +44 7969 375 889
Email: me@davemoffat.com

**Comment by nickjillings** [comment]
Added. To place a youtube link, you create a surveyentry node with the type youtube:

`<surveyentry id="video" type="youtube" url="https://www.youtube.com/embed/Mv9o8Ky8YpA">
    <statement>Please watch this video</statement>
</surveyentry>`

**Comment by djmoffat** [comment]
Great,

An on aside note, as I am still running on a bespoke core.js file, to allow passing of references to previous tests, I assume if I make a pull, that will break all that?

**Comment by nickjillings** [comment]
I’ve hoisted the dave_hack branch up to the top, so the custom edit will still work if you pull from that branch.

Nick

**Comment by djmoffat** [comment]
Great!

I will test it and let you know how I get on!

**Comment by djmoffat** [comment]
Amazing! It works well 

- are there options for sizing of the video? or is it just stuck at whatever resolution it is at? 
- Is it possible to get feedback on whether someone watched the video? or how long they spend on this survey question?

Just details now.

**Comment by nickjillings** [comment]
- Resizing, should be possible though easier for the spec to perhaps just show near full-screen.
- Not for youtube videos. It may be possible to detect how long someone stayed on the page for, though this should be a standard thing (so you could do enforced breaks).
