### ISSUE TITLE
Timeline comments disappear when clicking 'Next' prematurely

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#136]
From the example timeline.xml configuration file. 
I listen to fragment 0 and make a few comments, then click 'Next'. 
I'm told I haven't listened to all fragments, which is true, but then all my comments are gone. 

Interestingly, they are stored in the results XML, as is the error (great job!), so nothing is lost. But the subject might think all his answers are lost.

**Comment by nickjillings** [comment]
Silly mistake. Was doing `canContinue == false` not `canContinue = false`. Therefore the system was registering the failure and then actually loading the second page of the test which is identical!

Fixed now, it correctly breaks on error
