### ISSUE TITLE
Image element in interface

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#138]
Different scenarios (modes) possible: 
- Just an image, static, doesn't change with clicking/dragging different stimuli. 
- Associated with stimuli: different image shows depending on which fragment is playing. 
- Associated with stimuli but always showing: e.g. an AB(C) test where a saxophone, trumpet and bassoon are visible throughout... There's probably a better use case. 
- No audio, just images (for perceptual evaluation of visual stimuli). Could be 'implied' by there being a 'silence'/'no audio' mode for different audioelements. 

There should probably be a fixed place for it within every interface style, though size may be an optional attribute. 

In the case of associated images, there could be an `image` attribute for audioelements? In the case of a static image it could be a `page` attribute, or indeed a child of `page`.

**Comment by nickjillings** [comment]
Going through each of these:

1. Static image on page, easy enough to do with the interface container. Only issue is APE / multi-axis interfaces where more than one container may appear. Perhaps it makes sense to have multiple image elements?

2. That's actually quite a simple one to achieve. Also a nice and simple way to associate via attributes

3. Not sure how this would be different from the last one?

4. Yes it could be used as a hack anyway, so not supported but possible through the schemas.

Placing it should be easy, the only real issue is sizing.

**Comment by nickjillings** [comment]
Another use would be AB where each of the components have the image as their label. So rather than red it would be the different images and the user would have to select the images that best describe that case.

**Comment by nickjillings** [comment]
You could also have the scale markers be images / icons rather than text as well

**Comment by BrechtDeMan** [comment]
Those last two are pretty much what I had in mind for option 3. So you could have a different image showing based on what's currently playing (option 2), or you could have the images as icons for AB(X) or even APE/discrete/horizontal/MUSHRA (option 3). 

Size could be an optional height and/or width argument?

**Comment by nickjillings** [comment]
Cool. 

The size could be optional but probably better to set max boundaries to ensure  it doesn't shove the interface completely out of scope.

Scrolling on some interfaces (like MUSHRA) could be bad, so ideally the image needs to be big enough to be displayed but not so big it makes the scale really small!

It's probably going to come down to trial and error

**Comment by nickjillings** [comment]
Added fragment specific images to all interfaces (except ABX, where it doesn't make sense when you think about it, or timeline).
(2ed4b2e, 807b9c7, d260d7a)

**Comment by BrechtDeMan** [comment]
My thinking was this functionality could allow for other psychometric tests such as image-only (and hopefully in time video as well), leveraging the framework for other things than listening tests, in which case ABX does make sense. If it's not hard to implement, adding this functionality to ABX as well would make everything nicely homogeneous. 

No need to do this for timeline yet, though once videos are possible a video timeline annotation would be very useful to have as well.

**Comment by nickjillings** [comment]
For an image only approach though, how would that work? I mean if A and B have their own images, what is X meant to be? And if X has it's own image then that's the same as before with a static page image. I can add it in like the AB so it is there for completeness.

The timeline one shoulfn't be difficult I just hadn't got round to implementing it yet. This one I'm again unsure how an individual image will help when playing, but again I can add it in so it is there. And definitely on the video front will be very powerful!

**Comment by BrechtDeMan** [comment]
I'm thinking X will be either A or B, selected randomly. In images, this could test whether a subject can identify the right shade of colour (with or without colourblindness...). It's quite a limited use case, but if it's not a major rewrite I think it makes sense to support it. 

Unless there's functionality to have X being something different? E.g. X is the original signal, then is either A or B some version of X? Or is this 'AB with reference'?

**Comment by nickjillings** [comment]
So the ABX takes the AB pair and then randomly sets one to be the X as well. The user then selects either A or B which matches the X.

If we do images, then the issue comes as to how this works, since the images would then be shared between X and one of the A or B. I don't disagree that maybe there is a case where this could be useful, so I'll add it.

**Comment by nickjillings** [comment]
These are now in vnext branch, ready to be migrated over.

Ideally if we could test the following (which have examples):
* http://dmtlab.bcu.ac.uk/nickjillings/waet-vnext/test.html?url=tests/examples/timeline.xml
* http://dmtlab.bcu.ac.uk/nickjillings/waet-vnext/test.html?url=tests/examples/AB_example.xml
* http://dmtlab.bcu.ac.uk/nickjillings/waet-vnext/test.html?url=tests/examples/ABX_example.xml

**Comment by BrechtDeMan** [comment]
I assume it's intentional they're all the same image. Would be good to see if different images work too. 

Also, in ABX whichever button is selected becomes entirely green so the image is no longer visible. I wonder if the background could change colour while the image stays visible, and/or any transparent areas in the image should adopt the background colour (red or green). 

Works fine in Safari v8 otherwise.

**Comment by nickjillings** [comment]
Yeah they all work with individual images but copy-pasting it out was quicker.

Probably easier to make the overlay a lighter transparent green to indicate it's selected, will do that

**Comment by nickjillings** [comment]
![excerpt2](https://cloud.githubusercontent.com/assets/5649114/25390734/4a1ae66c-29cc-11e7-8aba-6b20d42dbc66.png)
