### ISSUE TITLE
Survey radio questions cause crash!

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#142]
If in a pre or post survey, a radio question is not manditory, and is not given an answer a crash occurs:
![screen shot 2016-08-24 at 12 54 50](https://cloud.githubusercontent.com/assets/4165324/17929687/fe53878a-69f9-11e6-93c9-eb117d893362.png)

As a pre-test question, this stops the test from loading

**Comment by nickjillings** [comment]
OK, will investigate
