### ISSUE TITLE
Post test surveys don't work

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#148]
From a user:

Post test surveys don't work (both Chrome and Safari). A blank box appears with a broken submit button.

![postsurvey](https://cloud.githubusercontent.com/assets/4103243/18636088/d2ebb37c-7e87-11e6-8434-e7dfd9272763.png)

I am running Mac OS X 10.10.5, the latest version of the WAET and the following were found by creating an AB comparison test via the test create tool.

**Comment by nickjillings** [comment]
It seems it's not specifically post test surveys, more that the next survey group does not show any text. More intriguingly, there is not one console error indicating something has gone awry.

**Comment by nickjillings** [comment]
Fixed in the new hot_fix branch
