### ISSUE TITLE
output file is being overwritten

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#151]
This is on Dev_main. the saved file (e.g.: from `test.html?url=tests/examples/horizontal_examples.xml`) is saved as `save-null.xml`, overwriting any existing `save-null.xml` file which previously existed in that folder.
This is a regression, maybe due to the introduction of `key` ?

**Comment by nickjillings** [comment]
OK, both this and possibly #150 are both showing null keys. This also seems to be the case with the earlier bugs #143 and possibly #144 which suggests the PHP server is doing something horrible.

I'll close this and merge with the currently open #143 as they are, essentially, the same root bug.
