### ISSUE TITLE
'Web Audio Evaluation Tool' and link to GitHub page on all interfaces

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#155]
It should be obvious from the test interface where to find the tool, so other people can use it if they come across a test.

**Comment by nickjillings** [comment]
Maybe. I'm not sure about a forced advertisement. A better way may be to have a more robust demonstration platform, such as a project Github IO site.

Perhaps on the test completion we could put our own message? That way it is a little more subtle.

**Comment by BrechtDeMan** [comment]
Agreed about the demonstration platform. For now I can use the hosted version and link to it from the documentation and readme, but it would be nice to have a git hook to the master branch or something similar, and improve the demos too. 

I was actually thinking of a very subtle message in the footer of the page (see '2016 Github, Inc.' at the bottom of this page) just so people know how the test was made. E.g. the text 'Web Audio Evaluation Tool' which is clickable.

I've found myself looking at source code of other tests just to find out who made it etc., so perhaps it makes sense to do this. Of course people could disable it, and would be welcome to, but I would just do it very subtle so hardly anyone could object. 

No strong feelings about it, just interested in your thoughts.

**Comment by BrechtDeMan** [comment]
Actually, this should probably be integrated with the version and commit number (although I appreciate the latter may be hard to automate). E.g. 'Web Audio Evaluation Tool 1.2.1 (2bf0c23)', where you can click 'Web Audio Evaluation Tool' to come to the GitHub page.

**Comment by nickjillings** [comment]
Yeah OK, a little footer is a good idea. For the finding the developers, I have seen one where opening the console triggers a welcome message! Which could be clever as well.

For the proper demonstration ones, yes we should do more. Perhaps with some iframes so multiple test pages are stacked on one page, or at least to have a more permanent link.

For the version, it should be fine for the full release numbers, we just have to remember to keep that up to date, for the git release I'm not sure if this is possible to automate in, as updating the git number causes a change, causes a commit, update the git number and so forth. But maybe there is a way.
