### ISSUE TITLE
Scrubber bar loops when audio doesn't (loop='false')

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#156]
With examples/project.xml, Safari 8.0.4, OS X.10.2

Scrubber bar keeps on going until you click 'Stop'. The audio stops so that's fine. Page 'loop' attribute is set to 'false' for this page, though to 'true' for previous page.

**Comment by BrechtDeMan** [comment]
Still true, also for ABX and MUSHRA and possibly others. 

Most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

**Comment by nickjillings** [comment]
Can we confirm if this is still an issue. Cannot replicate.

**Comment by nickjillings** [comment]
Open to the community, since cannot replicate

**Comment by nickjillings** [comment]
I may try and rejig this to use some other calculation features. Just to confirm the current behavior, since I cannot replicate @BrechtDeMan 
Does it still wrap around?
Or does it trail off into the distance...

**Comment by BrechtDeMan** [comment]
Still wraps around, though just my legacy Safari 8.0.4, not Chrome or Firefox. If Safari 9+ doesn't do it we can probably close this.

**Comment by nickjillings** [comment]
I still haven't been able to replicate this in any of the browsers. I will therefore close as I think it's a safari 8 issue.
