### ISSUE TITLE
Submitting impossible, blank dialog boxes

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#157]
With examples/project.xml: 

After the opening survey there are two blank dialogue boxes to click through before the test starts (see below for screenshot) - the button reads 'Start'. These are obviously not empty text nodes in the XML. 

The 'after page' survey disappears, also just blank boxes instead. 

Upon finishing the second, final page, the box is again blank, with only a 'Submit' button - *which cannot be clicked*. Submitting is therefore impossible. The console contains the following error message on Safari: 

    [Error] TypeError: undefined is not an object (evaluating 'textArea.value')
	proceedClicked (core.js, line 871)
	onclick (core.js, line 670)

Chrome: 

    Uncaught TypeError: Cannot read property 'value' of undefined
        at interfacePopup.proceedClicked (http://localhost:8000/js/core.js:871:56)
        at HTMLButtonElement.buttonProceed.onclick (http://localhost:8000/js/core.js:670:49)

Firefox: 

    TypeError: textArea is undefined 
        interfacePopup/this.proceedClicked() [core.js:871]
        interfacePopup/this.createPopup/this.buttonProceed.onclick() [core.js:670]

Tested on Chrome 54.0.2840.59, Safari 8.0.4 and Firefox 47.0 on OS X.10.2

<img width="1241" alt="screen shot 2016-10-17 at 10 48 52" src="https://cloud.githubusercontent.com/assets/4103243/19431577/4c768dde-9459-11e6-9fff-24f46a3f1d0c.png">

**Comment by nickjillings** [comment]
Is this at the top of the master branch? I believed this was fixed from #148

**Comment by BrechtDeMan** [comment]
Just wanted to say this is actually dev_main. Will rerun.

**Comment by nickjillings** [comment]
OK, dev_main is behind at the moment as it holds several unfinished bug fixes, then Tim showed his urgent issues so I pushed master forward to fix those for him.

I will at some point rebase the dev_main to restore the repo but haven't had the time to get that done yet to ensure dev_main remains stable

**Comment by BrechtDeMan** [comment]
Scratch all of the above (for branch 'hot_fix'). Sorry! 
Came across some unrelated issues mentioned in #154.
