### ISSUE TITLE
Radio interface no audio

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#159]
Invariably in the radio/Likert/discrete interface, the audio doesn't play for the first few seconds (it's looping but only the third time or so does the sound come on). Similarly, when switching to another sample, the previous sample keeps on playing for a while before switching. This is the only interface I've experienced this in. 

See most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

Safari v8.0.4 and Chrome v54.0.2840.71

**Comment by nickjillings** [comment]
I think this is actually an issue with the cross fade as this is the only example page with it set. In this case there is a serious issue

**Comment by nickjillings** [comment]
Fixed in master d44e980. Also fed through vnext and Dev_main branches
