### ISSUE TITLE
MUSHRA bug: submitting impossible

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#160]
Testing the MUSHRA interface from the examples in Safari, I was unable to submit. 

There's no 'Submitting' or 'Thank you' message, it just goes back to the interface, but 'Next' cannot be clicked. 

See most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

**Comment by nickjillings** [comment]
Is this still a bug? I've just run it and it completed fine for me?

**Comment by BrechtDeMan** [comment]
Yup works fine now for me.
