### ISSUE TITLE
AB interface: buttons not using full window width

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#162]
When having a large number of buttons, they only go to the sides when the screen is *really* wide. 

![ABCD... interface](https://cloud.githubusercontent.com/assets/4103243/20116472/99d85a4e-a5fc-11e6-841a-1d963c3bdc92.png)

See most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

**Comment by nickjillings** [comment]
@BrechtDeMan can you have a check that this works for your browsers? I'm using flex-boxes to automatically arange the AB selectors: http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test.html?url=tests/examples/AB_example.xml

If it works then can merge over to master

**Comment by nickjillings** [comment]
I've tested it on Windows (Chrome, FF, Edge) and OSX (FF and Safari v10)

**Comment by BrechtDeMan** [comment]
Safari v8 doesn't play nice with flex boxes. See attached. 
But works great in Chrome too, so perhaps we can consider this sorted. 
Maybe we need to alert users to not use Safari v8... or implement a workaround (non flex-box) for v8... 

![Safari v8 flex boxes](https://cloud.githubusercontent.com/assets/4103243/25177405/1da5b66c-2502-11e7-88a8-e8ccadcd5ff6.png)

**Comment by nickjillings** [comment]
I knew it was going to be a cry-baby.....

**Comment by BrechtDeMan** [comment]
I've worked around this before though... how about if you put it in a `display: flex;` wrapper, and make the individual elements (A button, B button, ...) `display: inline-block;`?

**Comment by nickjillings** [comment]
It's tempting to say so, given Safari 8 is over two years old now and is such a problem child. But a part of me also goes just because it's an inconvenience is no excuse.

**Comment by nickjillings** [comment]
Fixed now using in-line

**Comment by BrechtDeMan** [comment]
Confirmed in Safari v8
