### ISSUE TITLE
AB interface: toggling between stimuli not possible

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#164]
As opposed to e.g. the radio interface, in the AB example all other buttons go to 'Wait' when one sample is playing. While this is neat, what's not intuitive is that the other buttons cannot be clicked (greyed out), so in the case of a long or a looped sample, the workflow for switching between several samples is 'click play, click stop, click play, click stop, ...' rather than just clicking between the different samples i.e. 'click play, click play, click play, ...'.

Other interfaces (e.g. ABX) have better behaviour. 
<img width="1019" alt="AB interface" src="https://cloud.githubusercontent.com/assets/4103243/20116610/311d1ea8-a5fd-11e6-993e-654f2cb5fe61.png">

See most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

**Comment by nickjillings** [comment]
This is because the example has the value `playOne="true"` in the `<setup>` node. This means you cannot switch to another whilst one is playing.

**Comment by BrechtDeMan** [comment]
Ah... apologies. I will make it clear from the example and the wiki then ([XML specification](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/XML-specification) and [Features](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Features)). Wasn't aware of this feature. 
Any other new ones, please feel free to add a very brief bit about them.

**Comment by BrechtDeMan** [comment]
Also I disabled looping, as the combination of looping and 'playOne' doesn't make much sense as describe above.

**Comment by nickjillings** [comment]
Yeah I need to get better at updating the Wiki!

**Comment by BrechtDeMan** [comment]
Well you're already rocking the actual development... Hope this can become a day job for one of us at some point ;) 
Please don't take my issue logs as criticism on your outstanding work!
