### ISSUE TITLE
Horizontal interface cosmetic issues

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#165]
1. Button text does not change when clicked (while sample is playing), as opposed to e.g. AB, ABX, ... It just says 'Play'. 

2. When a sample is playing, the corresponding slider lights up (great!). However, the auxiliary lines are 
behind this pink plane so they disappear for the currently playing sample (see #166). 

3. It can have the error message "at least one element needs to be above the 75 mark", but this doesn't make sense when the end ticks are e.g. -50 and 50 like in the example. Perhaps this should be '75%'? (Same for other interfaces.)

**Comment by nickjillings** [comment]
1. Yep I'll fix that

2. Will fix as well, but probably keep track in #166 

3. The error messages are generated by the core, rather than the interface. However this may need updating here.

**Comment by BrechtDeMan** [comment]
3. Sure, but I think this might be true for other interfaces as well. E.g. a MUSHRA-style interface can also have numerical values from 1 to 5 instead of 0 to 100. Making it '75% of the range' is the most effective fix I can think of.

**Comment by nickjillings** [comment]
I may say add in custom messages. I think there is a bug for custom error messages

**Comment by nickjillings** [comment]
#133

**Comment by nickjillings** [comment]
All three of these points are now resolved in Dev_main (1b29ddb)
