### ISSUE TITLE
MUSHRA: highlighting in front of interface lines

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#166]
When a sample is playing in MUSHRA, the corresponding slider lights up (great!). However, the auxiliary lines are behind this pink plane so they disappear for the currently playing sample (see #165). 

See screenshot. 

<img width="1239" alt="screen shot 2016-11-05 at 11 18 30" src="https://cloud.githubusercontent.com/assets/4103243/20116668/7fefd764-a5fd-11e6-89ed-304dff45710a.png">

**Comment by nickjillings** [comment]
Fixed in 950f7ec
