### ISSUE TITLE
Timeline interface bugs

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#168]
The following workflow produces unexpected results:

Start the test, play first sample, click somewhere and comment. Then click Next. It says *'You have not played track Fragment 1.'* which is good. However, **it goes to the second page anyway**. The same thing happens on the second page even if you again only play one of the fragments. 

Safari v8.0.4

With most recent version from the [examples](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Examples).

**Comment by nickjillings** [comment]
Can you confirm which track (Dev / master) this is in, as I've recently solved some bugs on Timeline which caused similar effects.

**Comment by BrechtDeMan** [comment]
You're right! Solved as soon as this is merged into the master branch. 

http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/timeline.xml
vs 
http://webprojects.eecs.qmul.ac.uk/bdm30/dev_main/test.html?url=tests/examples/timeline.xml

**Comment by BrechtDeMan** [comment]
This is still an issue, see the above links which show the current state of both branches. 

The latter now gives the error
> element commentquestion: Schemas validity error : Element 'commentquestion': This element is not expected. Expected is one of ( audioelement, commentquestions, survey ).

**Comment by BrechtDeMan** [comment]
Sorry, tested cached version - but now there is no checking for playback even though the XML specifies this (new issue?)

**Comment by nickjillings** [comment]
@BrechtDeMan Yes that will be a new bug.

**Comment by BrechtDeMan** [comment]
New issue #185; closing this one.
