### ISSUE TITLE
Add survey parser (survey_parser)

### ISSUE THREAD

**Issue by nickjillings** [BrechtDeMan/WebAudioEvaluationTool#169]
Create a python script to extract the survey results from all pages/globals.

**Comment by BrechtDeMan** [comment]
Output could be CSV, JSON and/or XML. 

Related: I'd also want this to be part of `generate_report.py`, so you would automatically get statistics of the questions you asked. In particular, answers to any multiple choice question could easily be plotted as a pie chart, bar chart etc. This is already implemented, though the question ID ('age') is hard coded.

**Comment by BrechtDeMan** [comment]
From #205, for discussion:

> So the real danger with this is how to export certain data. We can create a generic parser which just gives the raw values, or should there also be certain overviews as well given. For instance should radio and checkboxes be given with percentages?

I would say the most general and urgent use case is someone who wants to get the data out of the XML structure, which can then be imported into Excel or similar, at which point percentages etc. are easy to calculate.

With regard to the structure, perhaps this could be something like a folder with one CSV file per question, named '1-number-age.csv' for the first question which is type='number', id=age, and which then contains one row per subject (id, response)?

Maybe an optional argument can toggle between 'one file per question' and 'one file per subject'?

**Comment by nickjillings** [comment]
Now creates a file for each survey element to hold the information, for example a comment question may be:

```csv
ids, durations, response
xxx, 2.45, blue
yyy, 1.45, red
zzz, 11.2, green
```

But a checkbox would be
```csv
ids, durations, option_a, option_b, option_c
xxx, 2.45, true, false, false
yyy, 1.45, true, true, false
zzz, 11.2, false, true, false
```

Files are named after their `id`, so `<surveyquestion id="test-question">` would make a file called `test-question.csv`

**Comment by djmoffat** [comment]
@nickjillings @BrechtDeMan Is this closed? As it doesn't seem to have made it to the main branch.

**Comment by BrechtDeMan** [comment]
You're right, it's on dev_main. I haven't tested it, so until you have this is 'in review'.

**Comment by nickjillings** [comment]
It's part of milestone 1.2.3, so it'll cross over once that is completed.

Nick
