### ISSUE TITLE
Fragment numbering from zero everywhere but APE

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#170]
I remember this was changed in APE, and other numbering is now possible (letters etc.). I think this should be universal. 

For AB and ABX, the letters are fine, though perhaps there could be an option to change to numbers, or lowercase capitals (just for uniformity, or use cases I'm not thinking of).

I suppose it could be optional, but I don't think anyone would object to the numbering starting at 1.

**Comment by nickjillings** [comment]
This is in progress (#37). Most (all I think) of the interfaces support either letters, capitals or numbering with a configurable starting point (a,b,c or x,y,z for instance).

This is only on Dev_main right now (0425ea2)

**Comment by BrechtDeMan** [comment]
Right, sorry. Close? 

Is 1 the default for all interfaces - and should it be? 
I'd say so, and I don't see this implemented at this point. 

Is there a wraparound after Z? Or AA AB AC ...? (Can't find an answer in the code)

**Comment by nickjillings** [comment]
I think the default (for numbering) is 1. I think it should for all number based interfaces (all except AB/ABX).

Yes they should auto wrap. However all numbering is taken care of by the individual test interfaces.
