### ISSUE TITLE
AB interface: buttons do not always show 'Stop' when playing

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#174]
It should only say Listen on fragments not playing, and Stop on the currently playing fragment. This is not the case, however: sometimes clicking the button doesn't make it show 'Stop'. 

The theory is that it works fine when playing the files in consecutive order (i.e. left to right), but when going back the buttons start misbehaving.

**Comment by nickjillings** [comment]
I see. It seems to happen mostly when clicking on a fragment whilst another fragment is playing. Very odd behaviour.

**Comment by nickjillings** [comment]
Fixed in 86e18e3
