### ISSUE TITLE
Stops current sample but doesnt start new sample

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#176]
I have an odd bug that seems consistent in Chrome

If I start a listening test and jump back and forth between samples that are individually looping, then every one in ten clicks will stop the current sound and no sounds will play - the playhead will still move and logs a play, but the track can never be heard.

This is not repeatable in safari, but is consistent across different samples.

**Comment by djmoffat** [comment]
an example is available here: http://webprojects.eecs.qmul.ac.uk/djm31/propellorTest/test.html?url=tests/testPages.xml

**Comment by nickjillings** [comment]
I've seen this around before but never been able to hunt it down. Chrome has this annoying 'energy saving' setup where any audio control functions are ignored if it thinks there is no audio playing through the current node (the idea to pick them up later). It is extremely buggy, with lots of people quite rightly upset with this unspecified behaviour.

Unfortunately there is no real solution except to stop (by clicking the stop button) and starting again. I will go and do some more digging on this to see if there is a solution.

Can you also confirm for me which branch you are on? I am assuming the master and most recent pull.

**Comment by nickjillings** [comment]
See #154

**Comment by djmoffat** [comment]
Yes, master most recent pull. I traced it down to something to do with linearRampToValueAtTime() but looks like you are right.

**Comment by nickjillings** [comment]
Yep, Chrome likes to ignore this if it thinks the audio has stopped playing! In some cases it is correct, but is undesired (and non-standard) behaviour. I'll see if I can do some more trickery, but right now we're sort of at their mercy
