### ISSUE TITLE
Test creator 'undefined' fields

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#181]
Some fields have 'undefined' as a name, e.g. under 'page' and 'audioelement': 
(see screenshots)
![waet-page-undefined](https://cloud.githubusercontent.com/assets/4103243/23454956/4111faa8-fe6e-11e6-9bc5-2646635b9746.png)

![waet-audioelement-undefined](https://cloud.githubusercontent.com/assets/4103243/23454975/553d3862-fe6e-11e6-9f89-5c449b7d9113.png)

**Comment by nickjillings** [comment]
Added to v1.2.2 as this is all the stuff to do with the test creator.

**Comment by nickjillings** [comment]
Dev_main
