### ISSUE TITLE
Test creator: 'URL' and 'Required sample rate' fields under audioelement

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#182]
### URL
This appears twice - not sure if one of them doesn't work and what it should be instead.

### Required sample rate

Is this not a test-level requirement, as the system sample-rate cannot be changed mid-experiment?

See screenshot. 

![waet-audioelement-undefined](https://cloud.githubusercontent.com/assets/4103243/23454975/553d3862-fe6e-11e6-9f89-5c449b7d9113.png)

**Comment by nickjillings** [comment]
Confirmed and added to v1.2.2

Two URLs and two Required Sample Rates are bugs here, there should only be one.

I'm actually unclear right now what the required sample rate is, but I will investigate

**Comment by nickjillings** [comment]
Dev_main
