### ISSUE TITLE
Test creator / general: empty 'survey' node not accepted

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#183]
An empty survey is not accepted by the XML validator, as loading such a test gives
> element survey: Schemas validity error : Element 'survey': Missing child element(s). Expected is one of ( surveyentry, surveyquestion, surveyradio, surveycheckbox, surveystatement, surveynumber, surveyslider, surveyvideo, surveyyoutube ).

However, the test creator creates a survey node by default before and after each page, and before and after the test, even when no survey elements are added.

**Comment by nickjillings** [comment]
Will update the schema to reflect the possibility of an empty `<survey>` node

**Comment by BrechtDeMan** [comment]
And a second action point of the test creator _not_ creating a survey node when no survey items are added, so that the XML is more compact and sensible? 

Or is that bad form?

**Comment by nickjillings** [comment]
No that's also reasonable and probably easier to do

**Comment by nickjillings** [comment]
Fixed in dev_main (a959902)
