### ISSUE TITLE
'Loudness' doesn't have any effect

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#184]
For instance in the following bit. Very different loudness values but no effect can be heard. 
Gain works fine. 

Same problem with the 'page' Loudness. 

`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="discrete"><exitText>Thank you.</exitText><survey location="pre"><surveyquestion id="name" mandatory="true" boxsize="normal"><statement>Name?</statement></surveyquestion></survey><survey location="post"><surveystatement id="mastersurveyafter"><statement>mastersurveyafter</statement></surveystatement></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface><interfaceoption type="check" name="fragmentMoved"></interfaceoption></interface></setup><page id="testpage1" hostURL="media/example/" randomiseOrder="true" loop="true" synchronous="true" labelStart=""><commentboxprefix>Comment on track</commentboxprefix><interface><title>Some feature</title><scales><scalelabel position="0">Strongly Disagree</scalelabel><scalelabel position="25">Disagree</scalelabel><scalelabel position="50">Neutral</scalelabel><scalelabel position="75">Agree</scalelabel><scalelabel position="100">Strongly Agree</scalelabel></scales></interface><audioelement url="1.wav" id="one"  loudness="-10"></audioelement><audioelement url="2.wav" id="two" loudness="-20"></audioelement><audioelement url="3.wav" id="three" loudness="-30"></audioelement><survey location="pre"><surveystatement id="testsurveybefore"><statement>testsurveybefore</statement></surveystatement></survey></page></waet>`

**Comment by nickjillings** [comment]
Part of a larger issue.

The loudness seems to be computed correctly, with buffers getting the correct LUFS
- 1.wav at -15.267468671877543
- 2.wav at -12.582209103247985
- 3.wav at -15.222426479170805

However, the playback gain parameter, which takes the buffer LUFS and calculates the appropriate gain to reach the target LUFS, is set to NaN. This is (correctly or not) ignored.

**Comment by nickjillings** [comment]
One line of code was causing the calculated loudness LUFS to be stored in the wrong place, causing a NaN to be calculated as the playback gain.

There is a safety catch to ensure that only a valid playback gain is used, otherwise a gain of 1 is used (no change).

Loudness of `<setup>` or `<page>` now works. Need to fix local loudness
Only in hot_fix 4e0fc9e

**Comment by nickjillings** [comment]
Fixed in master branch  020e767

**Comment by BrechtDeMan** [comment]
Confirmed on Chrome and Safari - thanks!
