### ISSUE TITLE
Timeline interface not checking for playback

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#185]
As first reported in #168 

No checking for playback even though the XML specifies this; you can play one and go to the next page without warnings. 

See 
http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/timeline.xml 
or
http://webprojects.eecs.qmul.ac.uk/bdm30/dev_main/test.html?url=tests/examples/timeline.xml
for current version

**Comment by nickjillings** [comment]
Fixed in 106becd
