### ISSUE TITLE
Custom result file names

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#186]
There is the option to choose a custom prefix for the saved files (by default save-[hash number].xml), but it currently does this:

> [path]/test.html?url=tests/testfile.xml&saveFilenamePrefix=yournamehere

gives the file name
> save-[hash number]**&saveFilenamePrefix**.xml

while this should be 
> yournamehere-[hash number].xml 

or similar. 

Documentation to be added once properly implemented. 

In the long term this URL argument should be replaced with an option in the XML specification.

**Comment by nickjillings** [comment]
This is actually a Python problem. The PHP system correctly interprets the parameters

**Comment by nickjillings** [comment]
This is now fixed in master following f0bbb5a
