### ISSUE TITLE
Scale Position 0-100, output value 0-1

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#189]
Hey,

Why is the scale position 0-100 but the output scale is 0-1? It seems odd to use two different scales.

perhaps we should standardise?

**Comment by nickjillings** [comment]
The scale position can be either 0-1 (float) or 0-100 (integer). The final output is between 0 and 1 to give the highest resolution (float point accuracy).

**Comment by djmoffat** [comment]
Great

this is now closed.
