### ISSUE TITLE
Test hanging and won't save

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#190]
Hey,

I have just had an issue with a test hanging and won't save 
![screen shot 2017-03-20 at 11 45 22](https://cloud.githubusercontent.com/assets/4165324/24098559/03272322-0d63-11e7-904d-d4392e32cb1a.png)

**Comment by nickjillings** [comment]
It has saved, the response says it has. Are you on the latest pull? The line numbers don't match up. Also which browser and version number?

**Comment by djmoffat** [comment]
Hey,

sorry, you are right, I was not on the latest pull. I have pulled and am now re-running (I don’t really like pulling constantly when trying to run a test, as I know previous pull is more consistent that continually changing test)

Browser: Safari Version 8.0.8
—
Dave Moffat
07969375889
me@davemoffat.com


On 20 Mar 2017, at 11:51, nickjillings <notifications@github.com> wrote:

It has saved, the response says it has. Are you on the latest pull? The line numbers don't match up. Also which browser and version number?

**Comment by djmoffat** [comment]
So, it seems to have done the same thing again, on the latest pull:

**Comment by nickjillings** [comment]
The latest pulls should now work. All the save communications are in one place now so it's a lot easier to maintain. Also there are distinct update() and finish() functions to ensure the nodes are properly updated.

**Comment by nickjillings** [comment]
OK, I've done some more work to this. There was an error in save.php which could have resulted in some saves not being stored properly. Fixed now in 8f23a5b
