### ISSUE TITLE
Set page positions

### ISSUE THREAD

**Issue by nickjillings** [BrechtDeMan/WebAudioEvaluationTool#191]
Allow the specific placement of pages in the randomisation pool. This allows pages to be placed first for training purposes or for filtering of subjects before the tests.
 
Requires specification attribute added to the `<page>` element.

Similar to #34

**Comment by nickjillings** [comment]
Each `<page>` node now has a new `position` attribute. This allows for the explicit positioning of pages within a test environment. Pages with a position attribute set also automatically have their `alwaysInclude` attribute set to true.

**Comment by nickjillings** [comment]
MWE:

```xml
            <page id='test-0' hostURL="media/example/" randomiseOrder='false' repeatCount='0' loop='true' loudness="-12" labelStart="10" label="number">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Page 0</title>
            </interface>
            <audioelement url="0.wav" id="track-0" label="x" />
            <audioelement url="1.wav" id="track-1" label="y" />
        </page>
        <page id='test-1' hostURL="media/example/" randomiseOrder='false' repeatCount='0' loop='true' loudness="-12" labelStart="10" label="number" position="0">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Page 1</title>
            </interface>
            <audioelement url="0.wav" id="track-2" label="x" />
            <audioelement url="1.wav" id="track-3" label="y" />
        </page>
        <page id='test-2' hostURL="media/example/" randomiseOrder='false' repeatCount='0' loop='true' loudness="-12" labelStart="10" label="number">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Page 2</title>
            </interface>
            <audioelement url="0.wav" id="track-4" label="x" />
            <audioelement url="1.wav" id="track-5" label="y" />
        </page>
        <page id='test-3' hostURL="media/example/" randomiseOrder='false' repeatCount='0' loop='true' loudness="-12" labelStart="10" label="number">
            <commentboxprefix>Comment on fragment</commentboxprefix>
            <interface>
                <title>Page 3</title>
            </interface>
            <audioelement url="0.wav" id="track-6" label="x" />
            <audioelement url="1.wav" id="track-7" label="y" />
        </page>
```

In the above example, the second page `test-1` is placed first, the rest are randomised

**Comment by nickjillings** [comment]
This is now in master

**Comment by ardaillon** [comment]
Hello,

It seems that the page ordering option with position attribute doesn't work properly, when several pages have a set position attribue.
This is due to the splice method being used on pagePool array inside the loop iterating on the pagePool array in core.js, line 1318.

I fixed it on my side by modifying the code like this : 

        var fixed = [];
        var fixedPagesIdx = [];
        pagePool.forEach(function (page) {
            if (page.position !== undefined) {
                fixed.push(page);
                var i = pagePool.indexOf(page);
                fixedPagesIdx.push(i);
            }
        });
        
        var nbPagesRemovedFromPool = 0;
        fixedPagesIdx.forEach(function (pageIdx) {
            pagePool.splice(pageIdx-nbPagesRemovedFromPool, 1);
            nbPagesRemovedFromPool = nbPagesRemovedFromPool + 1;
        });

Best,
Luc
