### ISSUE TITLE
RangeError: Invalid array buffer length (Chrome)

### ISSUE THREAD

**Issue by BSweeny** [BrechtDeMan/WebAudioEvaluationTool#192]
Trying quick set up - cannot access the .wav files - "LISTEN" button greyed out. Get error:

"Uncaught RangeError: Invalid typed array length
    at new Float32Array (native)
    at calculateMeanSquared (http://localhost:8000/js/loudness.js:87:17)
    at OfflineAudioContext.offlineContext.oncomplete (http://localhost:8000/js/loudness.js:61:26)"

Debugger shows array length  = -4 on further investigation. I'm new to all this so it is possibly my set up. Using Windows 10 Home, version 1607. 64-bit OS. Tried Chrome recent chrome Version 57.0.2987.110, also Mozilla Firefox most recent. Updated Java. Localhost server through Python (2.7) used also.

Desperate to use this program for audio listening test I need to run from my degree. Thanks for your help. Here is a screen shot:

![image](https://cloud.githubusercontent.com/assets/26670773/24321689/b5ba0cd0-114a-11e7-8a9e-67ea1f1a2c09.png)

**Comment by nickjillings** [comment]
Hi @BSweeny, thanks for getting WAET and reporting these issues.

Unfortunately I cannot replicate this issue (Chrome 56, updating to 57 now).

Have you tried running this in Edge as well?

It seems the audio files are not being loaded or loading incorrectly. Also can you ensure that you have the most recent (master branch) version. You can either perform a `git pull` command (if you cloned) or get it from (here)[https://github.com/BrechtDeMan/WebAudioEvaluationTool/archive/master.zip]

**Comment by BSweeny** [comment]
I re-installed from your link, but the same loading issue. The Python 2.7
command line when opened states win32  - could this be the problem?  (I
don't access this way I use cmd and point to the correct folder and
'pythonserver.py', or have opened 'Spyder' to run python with same
problematic results). cmd prompt accessing python server, is that all
python is doing, hosting a local server and the chrome browser or whatever
browser used is loading in it's plug-in's?

It's also temperamental "Loading Resources" hangs on all browsers at first
for 'index.html?'. Back button and reload generally resolves after a few
attempts. This might be significant?

Edge shows grayed out button for 'LISTEN'

**Comment by BSweeny** [comment]
OK..localhost using python 2.7 is not able to load the audio files after many hours of trying to find a bug. Downloaded most recent python 3.6.1 and works perfectly...Bri

**Comment by nickjillings** [comment]
OK, so it may be that Spyder or another python interpreter does not function then.

Did the python 2.7 show any errors?

Glad it is working for you know

**Comment by BSweeny** [comment]
Python did not show in errors using the 'pythonserver.py' in 2.7. I didn't use other python files as I could not run the test then. The' Loudness.js' file as seen in previous screen print on thread could not find/ load the audio files. When using 'debugger' and narrowing down the problem it appears the issue may be here (line 79 in loudness.js):

function calculateMeanSquared(buffer, frame_dur, frame_overlap) {
    frame_size = Math.floor(buffer.sampleRate * frame_dur);
    step_size = Math.floor(frame_size * (1.0 - frame_overlap));
    num_frames = Math.floor((buffer.length - frame_size) / step_size);

num_frames returns an array of -4 which is not possible so collapses there. It may be specifically the .js code that is not compatible with python 2.7 or the core.js?? - I'm only a mere physicist :) not a programmer. 

I'm trying to run a loudness perception test, but I think the LUFS feature is effectively normalising the peaks in each .wav now and any JND is imperceptible..using AB test template - is there a way to remove feature?

**Comment by nickjillings** [comment]
If you remove the `loudness=""` tag from the `<setup>` node in your XML, it will not loudness normalise. It will still go through loudness.js but the loudness values are not then used.

The error is being found in that function, but is more likely that the audio samples are too small. What is the length of your audio samples? Since num_frames = -4 must mean the frame_size (a fixed number for LUFS) is bigger than buffer.length (the length of your audio).

Nick

**Comment by BSweeny** [comment]
Each sound file is 12 seconds in length. I need them to be cut to 3 seconds, which I will do later on - unless there is a way to shorten the length of wavs in play back..

**Comment by nickjillings** [comment]
Can you email me one of the audio files (nicholas.jillings@mail.bcu.ac.uk) so I can see if there is perhaps a WAV issue causing this.

The num_frames = (N / 0.4*Fs) / (0.1*Fs). So if there are 12 seconds of audio then the only other possible outcome is that the sample rate is not correct in the wav file, causing the frame_size to be greater than the buffer length, giving a negative number.

**Comment by nickjillings** [comment]
I've added a partial fix on the master branch (if you update it will be there) to ensure the num_frames must be 1 or positive.

**Comment by BSweeny** [comment]
I'm sure I'm making some basic error - anyhow here is one of the .wav files
used.

**Comment by nickjillings** [comment]
Hi, sorry you need to actually email me rather than reply to GitHub (it will remove attachments)

**Comment by nickjillings** [comment]
This seems really weird! I can load the file perfectly well and it normalises it.

Can you load our remote host test here (http://dmtlab.bcu.ac.uk/nickjillings/waet/index.html?url=tests/examples/AB_example.xml) and see if it works for you?

If it doesn't, then there may be some other local issue here causing some unknown problem.

**Comment by BSweeny** [comment]
Remote host worked fine and could access the 'AB_example' samples with no
problem - ran perfect. On my machine Python 3.6 works too as a local host
but not 2.7. I continue to use 3.6 for the local hosting. Have you tried to
local host with python especially 2.7? Bri

**Comment by nickjillings** [comment]
No I haven't tried 2.7 on windows, but it does work on OSX. I will investigate that then but will close this bug since this is 'fixed' and open a new one for 2.7 with windows
