### ISSUE TITLE
Don't save partial results with same name

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#193]
It can be tedious to go through all 'saves' and manually determine which have completed and which haven't. 

While the partial saves can be very close to a successful save and may therefore want to be included, automatically including all partials can break analysis scripts and accidentally incorporate invalid results into the analysis. 

Perhaps 'partial-abc123.xml' or '_save-abc123.xml' would be a sensible naming convention.

**Comment by nickjillings** [comment]
Maybe. The partials should have an "incomplete" style tag in the save to differentiate them from analysis scripts.

In terms a cleanliness though, maybe storing them with an incomplete makes sense

**Comment by nickjillings** [comment]
Should be implemented in eb31372. Each file will save as:
update-"prefix/save"-"key".xml when intermediary. Upon test completion, the final test is saves without the "update-" and the intermediary file is deleted. This is only after the new file is confirmed as saved so should be safe.

Unable to test PHP right now, so will review until it can be tested.
