### ISSUE TITLE
Sticky volume slider bug

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#194]
When adjusting the volume, the mouse sticks to the slider and can't be un-stuck, meaning the test needs to be restarted and volume cannot really be adjusted. 

Chrome latest version

Also reported by @djmoffat

**Comment by djmoffat** [comment]
True, I have experienced a few times.

**Comment by nickjillings** [comment]
Is this only in Chrome?
Is there an error associated in the console?

**Comment by BrechtDeMan** [comment]
Only have it in the APE-style interface apparently, not with ABC. 
No errors. 

In Chrome as well as Safari (8). 

In Firefox, the slider jumps back to 0 dB as soon as you drop it and move away.

**Comment by nickjillings** [comment]
OK. I'll do a hot-fix later to correct.

**Comment by nickjillings** [comment]
It seems to only be the APE interface that causes a problem, which is very strange.

**Comment by nickjillings** [comment]
Fixed in master in commit 68b5589
