### ISSUE TITLE
Randomising pages on global setup is only selectable via a 'undefined' check box

### ISSUE THREAD

**Issue by callumgoddard** [BrechtDeMan/WebAudioEvaluationTool#197]
<img width="594" alt="screen shot 2017-04-14 at 13 30 33" src="https://cloud.githubusercontent.com/assets/1432820/25043297/c2a2f660-2116-11e7-87b6-e26f98caf6af.png">
The randomise tick box doesn't appear to work, but there is an additional 'undefined' checkbox in the global settings, this appears to randomise the question order. Screenshot attached.

**Comment by nickjillings** [comment]
Thanks for spotting this.

There are a lot of bugs drawn from how the test creator tool was made. I'm actually in the process of ripping the whole lot down and re-building!

**Comment by nickjillings** [comment]
Dev_main
