### ISSUE TITLE
Test creator: generate AB(X) test from list of samples

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#200]
As far as I'm aware, you now have to specify each possible combination in an AB/ABX test in the test creator, which is impossibly tedious for a high number of samples. 
But really what you want is to automatically make a set of pages (AB, AC, AD, BC, BD, CD), perhaps with the option of including AB as well as BA (where audioElement order is not randomised), and whether or not 'AA' is allowed (e.g. as a check). 
Beyond this the ordering would be randomised as indicated by the `randomiseOrder` flags, a number of pages selected from the 'pool' as indicated by `poolSize`, and so on - nothing new.

I don't think many bells and whistles would be needed here, as e.g. repetition can be introduced by just copying a chunk of the XML file. 

Once this is done I'll make an AB test video demo.

**Comment by dreamk73** [comment]
Is there still any work on this? I created an AB test by hand by copying and pasting different AB pairs in the xml definition file and changing the names and waveforms etc. But as you said it is quite tedious when you have a lot of samples.

**Comment by nickjillings** [comment]
This is part of v1.2.3 milestone which means it should be developed for the next release candidate. This is a slightly ancillary request because it is only for one interface type. But mostly it's actually quite time consuming to implement. However since it is for the next milestone it will be acted upon sooner than later, but I won't make any guarantee as to when it will be implemented.

**Comment by nickjillings** [comment]
As a first implementation, I'll simply enable dragging fragments onto a "page" element and have it auto-populate the data.

The next step is to move it up to doing AB in the introduction spaces for AB(X) tests and others.

Key is to keep these things as generalised as possible.

**Comment by nickjillings** [comment]
Try it on http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test_create.html
