### ISSUE TITLE
Mandatory and value-restricted number questions not enforced

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#201]
Mandatory number questions can be left empty without any warning, and the `min` and `max` attributes are seemingly ignored as well. 

E.g. 

    <surveyentry type="number" mandatory="true" id="age" min="12">
           <statement>Please enter your age (example mandatory number question)</statement>
    </surveyentry>

can be skipped without entering any value, or entering '3' (less than the minimum 12).

**Comment by nickjillings** [comment]
Fixed  in 1f183e6
