### ISSUE TITLE
Scale range check not working with AB interface - possibly with others

### ISSUE THREAD

**Issue by callumgoddard** [BrechtDeMan/WebAudioEvaluationTool#202]
After updating to the latest branch no checks appear to happen when using: <interfaceoption type="check" name="scalerange" min="25" max="75"></interfaceoption> to prevent you being able to press submit if you haven't made a selection. Its possible to submit without having moved/selected any options.

**Comment by nickjillings** [comment]
It got disabled somewhere along the way. Re-activated
