### ISSUE TITLE
Test Creator gets stuck on a black page after selecting an interface

### ISSUE THREAD

**Issue by callumgoddard** [BrechtDeMan/WebAudioEvaluationTool#204]
Screenshots show when you open the test creator, you can start to make a new test, then select an interface. But after that you are presented with a black interface selection screen.  Pressing back takes you back to the first test creator page where you can drag in a pre-made xml file.

<img width="834" alt="screen shot 2017-04-21 at 16 29 06" src="https://cloud.githubusercontent.com/assets/1432820/25284791/1054fd88-26b0-11e7-8b2a-be260b949f32.png">
<img width="816" alt="screen shot 2017-04-21 at 16 29 14" src="https://cloud.githubusercontent.com/assets/1432820/25284793/11a666cc-26b0-11e7-9821-6cf00c9cc5a6.png">
<img width="832" alt="screen shot 2017-04-21 at 16 29 18" src="https://cloud.githubusercontent.com/assets/1432820/25284795/130d1740-26b0-11e7-9707-09dbd0d7c606.png">

**Comment by nickjillings** [comment]
Thanks.

I'm going to reject this purely because the code for this won't exist in the next 24-48 hours as I am finally ripping apart the test creator this weekend

**Comment by colemanwma** [comment]
Hi Nick,
I'm getting exactly this issue. I've downloaded the zip from GitHub today and run it on a web space and locally - both return the same. Tried it in Chrome and Safari.
Are you still working on the test creator?
Thanks,
Bill

**Comment by nickjillings** [comment]
Yep, it's currently in the development branch. You can either download the development or, if you just need the test creator, you can get an up-to-date version here:

- Dev_main: http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test_create.html
- vnext: http://dmtlab.bcu.ac.uk/nickjillings/waet-vnext/test_create.html
- master: http://dmtlab.bcu.ac.uk/nickjillings/waet/test_create.html

**Comment by nickjillings** [comment]
The Dev_branch is here: http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test_create.html

It's quite stable but it may be better to wait until the vnext is ready to use as right now it's all in a transitional state between two slightly different specifications. So a test made on the Dev branch may not work in the master right now.

**Comment by colemanwma** [comment]
Thanks Nick - much appreciated. Any idea of when the vnext will be ready to use?

**Comment by colemanwma** [comment]
Nick - thanks for the links to the different test_create.html files.

I've used the waet_dev/test_create.html (the other two point to the WAET 1.2.0 version) to start putting together a test. However, this still won't run for me in either the master or the Dev_main versions. Master throws an error on the .xml file (first screenshot), the Dev_main says it's Loading resources but just sits there (second screenshot). 

If I point it at pool.xml in the same folder, or one of the examples (tests/examples/AB_example.xml) those pages load and the tests work but have a momentary 'page unresponsive' message which goes away.

<img width="748" alt="screen shot 2017-06-07 at 14 26 41" src="https://user-images.githubusercontent.com/29146847/26881046-2f31c472-4b8e-11e7-815f-2474ce59202e.png">

<img width="793" alt="screen shot 2017-06-07 at 14 26 54" src="https://user-images.githubusercontent.com/29146847/26881070-43152e34-4b8e-11e7-9369-76c0990b41e8.png">

Have I missed something critical in the test setup or is this more likely to do with the update you're working on currently? If so, do you have an idea of when that might be complete?

Thanks,

B

**Comment by nickjillings** [comment]
Are you sure then that your XML is complete. It will hang like this if it gets a fatal error, usually being unable to load an audio file.

I will be pushing for it probably this weekend but other deadlines are being pushed so far.

**Comment by nickjillings** [comment]
It actually looks like you've saved the XML as a web page, rather than the XML. The first error says there is a <body> tag in your code.

You did hit export XML on the top left of the test creator and saved that to XML?

**Comment by colemanwma** [comment]
The 'export XML' button in Safari loaded a page which I was saving as 'web archive' (I was then manually changing the extension to .xml). Once I save that page as 'page source' it works in v1.2.1 of WAET, so I'm making progress.

Thanks for your time Nick. Much appreciated.

**Comment by nickjillings** [comment]
Yeah Safari behaviour is pretty non-standard on some things. Trying to get every renderer to work is quite a task.

Because of the spec. changes however, if you build it in the dev_main version you'll have to use the dev_main branch to run. It isn't actually that different in the core test code since this push is to update the test_creator so it should be perfectly stable for you to use.

But obviously, make sure you test your test before deploying!

**Comment by fuyang2032** [comment]
The same problem exactly. When designing an ABX test, even though the designing interface appears when using the creator in Dev_branch, it seems not to be the proper interface for ABX (cannot find a place to design the content of X).

**Comment by nickjillings** [comment]
Yep, the new test creator is still only in the Dev_main. Hopefully next week I can spend some time and complete this (admittedly very delayed) push.

The AB(X) is designed to take either the A or B and copy it to present it as X. Which one is picked is given in the result. If you fix the AB to be one or the other every time, you may get bias. So WAET will automatically pick this for you.

If you feel this behaviour is undesired, or you have a suitable alternative, then please raise an issue thread.

**Comment by fuyang2032** [comment]
Thank you so much nick! Got the idea. 

And there may be also something wrong during the execution of ABX_example in the Dev_main (X does not appear, neither A nor B can be chosen by click)
![image](https://user-images.githubusercontent.com/26958604/27482583-f36214f4-5819-11e7-89b2-2bcd794abd73.png)

The ABX_example in vnext is fine as I tried, but it goes wrong after modified by the creator in the Dev_main
![image](https://user-images.githubusercontent.com/26958604/27482724-77e3c8b2-581a-11e7-9e2c-540d8c2272dd.png)

Thanks again for your support and hard work!

**Comment by nickjillings** [comment]
Ok thanks. Can you raise this as a new issue for me?

Thanks

On 23 Jun 2017, at 14:52, Yang Fu <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you so much nick! Got the idea.

And there may be also something wrong during the execution of ABX_example in the Dev_main (X does not appear, neither A nor B can be chosen by click)
[image]<https://user-images.githubusercontent.com/26958604/27482583-f36214f4-5819-11e7-89b2-2bcd794abd73.png>

The ABX_example in vnext is fine as I tried, but it goes wrong after modified by the creator in the Dev_main
[image]<https://user-images.githubusercontent.com/26958604/27482724-77e3c8b2-581a-11e7-9e2c-540d8c2272dd.png>

Thanks again for your support and hard work!
