### ISSUE TITLE
Survey parser

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#205]
No (Python) parser for survey results as of yet. 
Could also be a webpage/CSV exporter etc.

**Comment by nickjillings** [comment]
So the real danger with this is how to export certain data. We can create a generic parser which just gives the raw values, or should there also be certain overviews as well given. For instance should radio and checkboxes be given with percentages?

**Comment by BrechtDeMan** [comment]
I would say the most general and urgent use case is someone who wants to get the data out of the XML structure, which can then be imported into Excel or similar, at which point percentages etc. are easy to calculate. 

With regard to the structure, perhaps this could be something like a folder with one CSV file per question, named '1-number-age.csv' for the first question which is `type='number'`, `id=age`, and which then contains one row per subject (id, response)?

Maybe an optional argument can toggle between 'one file per question' and 'one file per subject'?

**Comment by nickjillings** [comment]
Note #169

**Comment by BrechtDeMan** [comment]
Oh yeah - rather unsemantic name so didn't find that one. Apologies. Either can be closed.

**Comment by BrechtDeMan** [comment]
Closing duplicate.
