### ISSUE TITLE
Scale range check prevents questions being submitted

### ISSUE THREAD

**Issue by callumgoddard** [BrechtDeMan/WebAudioEvaluationTool#207]
When using the scale range check:
<interfaceoption type="check" name="scalerange" min="25" max="75"></interfaceoption>

you are unable to submit a question. Removing that interface line allows for questions to be submitted.

Screen shot showing the issue.
![screen shot 2017-04-24 at 16 02 02](https://cloud.githubusercontent.com/assets/1432820/25343591/718ecb20-2907-11e7-90a4-b995fd393915.png)

Tested in AB interface.

**Comment by nickjillings** [comment]
Yep, I just discovered that as well. Already fixed!

**Comment by callumgoddard** [comment]
Hahaha yeah I just saw the most recent commits!
