### ISSUE TITLE
Odd Likert bug (mutually exclusive rows)

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#210]
Sometimes, two rows in the `radio_example.xml` are 'mutually exclusive', i.e. it's not possible to select one option in row 1 and in row 2. Not always the same two rows, or the first rows clicked, or even adjacent rows. 

Try for yourself on http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/radio_example.xml, or see below.

![waet-discretebug](https://cloud.githubusercontent.com/assets/4103243/26122566/41067340-3a78-11e7-8cd2-247c0ff132c1.gif)

**Comment by BrechtDeMan** [comment]
It's a problem with `alwaysInclude` - somehow the always included one can also be selected again. So with 'zero' as `alwaysInclude` you could get 'zero one two three' but also 'zero zero two three'. This in itself is undesirable behaviour. 

In addition to this, it appears to be impossible to select any value for one zero while also selecting anything for the other, as per the above.

**Comment by nickjillings** [comment]
Fixed in 9099f13 and commited to master. Actually was a bug in the pool selection process.
