### ISSUE TITLE
MUSHRA sliders scale with window

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#211]
... and as such, even with a very tall window it is impossible to see what's below. Conversely, when making the window very small, the sliders completely collapse. 

I would imagine the desired behaviour is to stop scaling the sliders (at a certain point at least), so that you can see everything at once on a big screen. 

![waet-mushra](https://cloud.githubusercontent.com/assets/4103243/26126328/7f3bf0d8-3a85-11e7-9b49-b71f7ceab834.png)

**Comment by nickjillings** [comment]
Fixed in e7e501e
