### ISSUE TITLE
Multiple sort buttons in MUSHRA interface

### ISSUE THREAD

**Issue by hagenw** [BrechtDeMan/WebAudioEvaluationTool#212]
I have a small problem with the MUSHRA interface. Every time I click on the next button to proceed to the next page an additional sort button is added to the interface, see

![mushra_sort](https://user-images.githubusercontent.com/173624/27275439-b2d2291e-54d7-11e7-9aed-f2ddce052a8b.png)

So far I was not able to figure out where in the source code files this is happening. Could you maybe give me a hint how to fix this?

**Comment by hagenw** [comment]
Sorry, I didn't realize that I was not using the master, but the `Dev_main` branch. There I was able to find it and I guess the problem should be somewhere here near [this line](https://github.com/BrechtDeMan/WebAudioEvaluationTool/blob/Dev_main/interfaces/mushra.js#L251)

**Comment by nickjillings** [comment]
Merged your fix in, thanks for the spot and fix! Makes our lives much easier!

The Dev_main should be stable for most things, however these new features sometimes crop up issues. Unless you specifically need a feature in the Dev_main, it is better to use the master branch.
