### ISSUE TITLE
How to read the result directly from the 'saved file'?

### ISSUE THREAD

**Issue by fuyang2032** [BrechtDeMan/WebAudioEvaluationTool#216]
Hi, as I'm still struggling with the result analysis using python script, would you please provide guidance that how to read the result directly from the downloaded 'saved file'?

For example, if I got the following script generated by ABX_example, how to know if the X is picked up correctly or not? (The fact is that test-0 is incorrectly picked up, and test-1 is correctly picked up)

Thank you!

![image](https://user-images.githubusercontent.com/26958604/27598993-21280efa-5b5f-11e7-98f3-96144e4f90e8.png)

![image](https://user-images.githubusercontent.com/26958604/27599015-304e1d34-5b5f-11e7-89fe-22736087e273.png)

![image](https://user-images.githubusercontent.com/26958604/27599032-4582957c-5b5f-11e7-81e3-a7041478d04e.png)

![image](https://user-images.githubusercontent.com/26958604/27599047-536f8dd4-5b5f-11e7-83f6-5b030a0804f6.png)

![image](https://user-images.githubusercontent.com/26958604/27599058-5f0e432e-5b5f-11e7-95a5-204447699423.png)

**Comment by nickjillings** [comment]
Each `<audioelement>` node has a `<value>` node which reports the actual value of the fragment. In the AB/X tests a `<value>1</value>` means it was the one that was selected. The X should always be 0.

**Comment by nickjillings** [comment]
There was a bug in the ABX code I've just seen which caused all the values to be false! This is now fixed in commit 15e85d8

**Comment by fuyang2032** [comment]
All right now! Thanks nick
