### ISSUE TITLE
Discrepancy between numbers on interface and in error messages

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#22]
E.g. when you haven't played fragment 1 yet, it will say 'You have not played fragment 0 yet.', as per earlier convention.

**Comment by BrechtDeMan** [comment]
Have pushed a fix but it might be inconsistent with the rest of the code; please check @nickjillings

**Comment by BrechtDeMan** [comment]
Apparently the code in `core.js` doesn't do anything (can it go?)

Have now fixed it in `ape.js`, seems to work.

**Comment by nickjillings** [comment]
The core.js will affect every other interface. Because ape.js has a slightly unique layout (mutli-axis) the code is over-ridden from the default in core.js

**Comment by BrechtDeMan** [comment]
Ah got it! In that sense, is my initial commit still correct, or perhaps I should revert it? (I added 1 to every getPresentedId for missing comments / plays / moves)

**Comment by nickjillings** [comment]
getPresentedId should be returning the presented ID!! So somewhere it is going wrong for APE. I will look at this soon

**Comment by BrechtDeMan** [comment]
I believe it is already fixed (see second commit above) - and I have reverted my changes to core.js so that it works as before.

**Comment by nickjillings** [comment]
The ape.js now uses the getPresentedId, that way if the markers are letters then they are correctly mapped. We need to build a catch if the markers are 'none' as they will be meaningless.
