### ISSUE TITLE
Test creator show default values

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#222]
To make more easy to use, show default values (in grey placeholder text), or in the case of dropdown menus select default option (sometimes this is simply 'Default').

This can avoid confusion in case of ambiguous or less semantic field names, e.g. is 'Repeat Page N-times' 0 or 1 by default? (repeat once may mean occur twice, I'm not even sure)

**Comment by nickjillings** [comment]
All of the above are now in the test_create Dev_main (cff3991).
