### ISSUE TITLE
ABX: select which is X

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#223]
Currently, the X is randomly selected from A or B. To facilitate block-based design, where for instance X is equal to A as often as it is equal to B, and/or where each pair occurs twice, once with one sample as reference and once with the other, it should be able to force one sample to be equal to X. 

The most semantic and least disruptive way seems to be to reuse the 'reference' attribute, as suggested by @nickjillings. 

This is needed for a test in the medium term, so it's definitely relevant and I'm therefore flagging this as 'priority'.

**Comment by nickjillings** [comment]
Is this urgent now?

**Comment by BrechtDeMan** [comment]
It is actually! 

For each pair of samples which are to be compared, the following four orders should all appear: 

A, B, X=A
A, B, X=B
B, A, X=A
B, A, X=B

**Comment by nickjillings** [comment]
If one element of the two given is of type="reference", then that will be chosen as the "X" fragment.

If no element is of type reference, then one will be selected at random.

If both are given as type of reference, the first should be selected (but down to browser logic so avoid).
