### ISSUE TITLE
Silly ABX bug

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#224]
Silly but quite important bug: in ABX, you can quite easily see which one is 'X' just based on which loads first... 

Only a problem with the first one, and if they don't all load during the pre-test survey. But still. 

<img width="1437" alt="screen shot 2017-08-23 at 20 58 44" src="https://user-images.githubusercontent.com/4103243/29633260-faec480a-8845-11e7-8faf-5fd1c16d7c4a.png">

**Comment by nickjillings** [comment]
Patch for the issue, but not a great fix. Would be made better once objectified the entire test suites in v1.3.0

**Comment by BrechtDeMan** [comment]
Don't think this works yet I'm afraid. Running the fixed code but still seeing all three percentages.

**Comment by nickjillings** [comment]
Should now be fixed in 3357a4c (hot_fix)

**Comment by BrechtDeMan** [comment]
Looks like it - thanks!
