### ISSUE TITLE
ABX buttons don't always react

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#229]
See below: the A and B button sometimes go to 'Stop' (the intended behaviour), but often stay at 'Listen' - so it doesn't feel responsive and can lead to errors and frustration. See GIF below. 

![abx-buttons](https://user-images.githubusercontent.com/4103243/30297228-f78def44-973e-11e7-9555-98e8d2deb507.gif)

In general, the UI could feel a bit more responsive if the box was highlighted when it was playing (e.g. the contour around the bottom could light up), not just the comments, which aren't always there.

**Comment by nickjillings** [comment]
Confirmed, but I do feel like I've tackled this before.

Anyway, confirmed it exists so will fix

**Comment by BrechtDeMan** [comment]
You're right: #174 

Thanks for confirming.
