### ISSUE TITLE
Calibration test tones distorting

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#23]
Should be made so that they do not go beyond full scale. From about halfway the scale, the sine becomes a square wave, presumably because of hard clipping at 0dBFS.

**Comment by nickjillings** [comment]
It needs some more explanation. The red slider is 1k but it affects the global level (including that of the test). The idea is the user should set the 1k slider so the tone is comfortable, then set the others so they are level. But yes perhaps the default starting point should be -6dB.

**Comment by BrechtDeMan** [comment]
That's a good point, but whatever the range, the audible clipping should be avoided. My guess is this is because the sine goes beyond full scale and therefore gets clipped to a square-ish wave. 
Obviously the harmonic distortion renders the level setting useless, as the overtones created through this distortion could be very much audible even if the fundamental is not.

**Comment by BrechtDeMan** [comment]
I also notice that the top frequency (16k I suppose) has a fair bit of aliasing at 44.1kHz, but this must be due to the clipping as well. So the top of the scale should be (at the most) full scale, otherwise you will have components due to both creation of harmonics and aliasing of those harmonics around the Nyquist frequency.

**Comment by nickjillings** [comment]
I do want to fix this, perhaps there is a better calibration test we can use?

My understanding was the API allowed free form outputs of above 1.0 in the float world, as the OS audio drivers only clip if, when combined with the final output gain, it would clip.

Perhaps it should be that the maximum slider value generates a 1.0f output?

**Comment by BrechtDeMan** [comment]
Yes I think that would be the expected approach, but I'm not sure. Something is clipping it (also at low system levels), if it's not the API then it is the browser or something at OS level.

**Comment by nickjillings** [comment]
I'd say it is either OS and/or browser. Either that or the web audio API has been changed to have only normalised output (havent looked at that part for a while). Either way, all the possible isues have the same solution, so that's OK.
