### ISSUE TITLE
Comments disappeared

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#230]
Some time over the past few commits, the audioelement-specific comments seem to have disappeared **in the dev_main branch**... 

See http://webprojects.eecs.qmul.ac.uk/bdm30/dev_main/test.html?url=tests/examples/APE_example.xml vs http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/APE_example.xml

**Comment by nickjillings** [comment]
Hence the name Dev_main. It is the development branch.

Currently the APE is being converted into a modular system and some things are broken until they are re-implemented.

**Comment by BrechtDeMan** [comment]
Ah, right! Sorry. 

I didn't find what broke it so I thought it might have been an unexpected and unwanted side effect.

**Comment by nickjillings** [comment]
And they're back!
