### ISSUE TITLE
Autocreate saves folder if it doesn't exist

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#231]
Can we get it, so that it can auto create a saves folder if one doesn't exist?

**Comment by nickjillings** [comment]
Tested for Python but not for PHP now as cannot connect to server.

**Comment by nickjillings** [comment]
Tested and works with PHP, but only if the entire directory has write permissions on it. So handy but may not actually help. The test url php/test.html will be more useful to determine save status
