### ISSUE TITLE
Remove back button from survey

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#232]
How can we remove the back button from the survey

**Comment by nickjillings** [comment]
This would require a specification change to hide.

**Comment by BrechtDeMan** [comment]
Dave - as I think a 'hack' will help you out; see core.js line 1102:

        if (this.currentIndex > 0)
            this.buttonPrevious.style.visibility = 'visible';
        else
            this.buttonPrevious.style.visibility = 'hidden';

Removing this or setting both to hidden should do the trick. Also add `visibility: hidden;` to `button#popup-previous` in core.css. 

If I understand correctly this may be to deal with an issue arising from #227 (randomisation of survey questions) where clicking back has unintended consequences when the order is randomised. 

Though I agree this would be good functionality to have anyway.

**Comment by nickjillings** [comment]
The randomisation is calculated once and then fixed, so the back order should be correct.

If there is a failure somewhere in hitting back, that's a real bug

**Comment by nickjillings** [comment]
This is now implemented in Dev_main:

```xml
<survey location="pre" showBackButton="true|false"> ... </survey>
```

It will default to true if undefined, so is an explicitly hide system.

This will propogate through to master on completion of v.1.2.3

**Comment by nickjillings** [comment]
Added the showBackButton query to test create. http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test_create.html
