### ISSUE TITLE
Survey questions randomisation - Back Button

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#233]
The survey questions, 

When you press the back button, seems to cause some issues, where the answers change. I think this is due to the randomisation effect.

**Comment by nickjillings** [comment]
Can I have a little more information (and a MWE).

**Comment by djmoffat** [comment]
Sure,

If I select an answer on a survey question, where the survey options are randomised, and then click next, when I click back - to change my answer - the option selected is not the same as the answer I selected. I think this happens because of the randomisation effect.

MWE:
`<?xml version="1.0" encoding="utf-8"?>
    <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="APE" projectReturn="save.php" randomiseOrder='true' poolSize="2" loudness="-23" calibration="true">
            <survey location="before">
                <surveyradio id="rating" randomise="true">
                    <statement>Please select and option</statement>
                    <option name="bad">Bad</option>
                    <option name="poor">Poor</option>
                    <option name="good">Good</option>
                    <option name="great">Great</option>
                </surveyradio>
                <surveyradio id="number" randomise="true">
                    <statement>Please select and option</statement>
                    <option name="1">1</option>
                    <option name="2">2</option>
                    <option name="3">3</option>
                    <option name="4">4</option>
                </surveyradio>
            </survey>
            <metric />
            <interface />
        </setup>
        <page id='test-0' hostURL="media/example/" >
            <interface />
            <audioelement url="0.wav" id="track-0" />
        </page>
    </waet>
`

**Comment by nickjillings** [comment]
I believe it is fixed in 3edfddb. Seems the checkbox ones are OK, just the radios had an issue upon reload.
