### ISSUE TITLE
Custom result file names stopped working? 

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#235]
My results are all being stored as 'save-[hash].xml', even visiting this link: webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/APE_example.xml&saveFilenamePrefix=customname

See also the previously resolved issue #186 

EDIT: with the newest master this doesn't even save, see #234

**Comment by nickjillings** [comment]
Fixed in 277bo72
