### ISSUE TITLE
repeatCount and synchronous not working (ABX)

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#241]
With no looping mode specified I can't get  to do anything. 

MWE below: here I get 4 pages (no `repeatCount`) and every stimulus starts from the beginning when toggling between them (no `synchronous`). 

The latter does work with `loop` active, but I don't think that's the intended behaviour? 

<?xml version="1.0" encoding="utf-8"?>
        <waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
            <setup interface="ABX" projectReturn="save.php" randomiseOrder='true' sampleRate='96000'>
                <survey location="before">
                    <surveystatement id="test-intro">
                        <statement>In this interface, you will be presented with a small number of ABX tests. Select the option A or B which is identical to X. The stimuli are versions of the same content with subtle quality differences. 

    Make sure your system (computer, audio interface, and/or DAC) is set to a sample rate of 96 kHz. Restart your browser for this change to take effect. </statement>
                    </surveystatement>
                    <surveyquestion id="sessionId" mandatory="true" boxsize="small">
                        <statement>Please enter your name.</statement>
                    </surveyquestion>
                    <surveyquestion id="equipment" mandatory="true" boxsize="large">
                        <statement>Please describe your playback chain and listening situation (audio interface, headphones or speakers make and model, acoustic environment, background noise).</statement>
                    </surveyquestion>
                </survey>
                <survey location="after">
                    <surveyquestion id="postcomments" boxsize="large">
                        <statement>Please enter any extra comments you would like to share. </statement>
                    </surveyquestion>
                </survey>
                <metric>
                    <metricenable>testTimer</metricenable>
                    <metricenable>elementTimer</metricenable>
                    <metricenable>elementInitialPosition</metricenable>
                    <metricenable>elementTracker</metricenable>
                    <metricenable>elementFlagListenedTo</metricenable>
                    <metricenable>elementFlagMoved</metricenable>
                    <metricenable>elementListenTracker</metricenable>
                </metric>
                <interface>
                    <interfaceoption type="check" name="fragmentPlayed" />
                    <interfaceoption type="show" name="page-count" />
                    <interfaceoption type="show" name='comments' />
                </interface>
            </setup>
            <page id='zeroone' hostURL="media/example/" repeatCount="2" synchronous="true">
                <commentboxprefix>Comment on fragment</commentboxprefix>
                <interface>
                    <title>Select which of A or B is closest to X</title>
                </interface>
                <audioelement url="0.wav" type="reference" id="zr" name="zero"/>
                <audioelement url="1.wav" id="o" name="one"/>
            </page>
            <page id='onezero' hostURL="media/example/" repeatCount="2" synchronous="true">
                <commentboxprefix>Comment on fragment</commentboxprefix>
                <interface>
                    <title>Select which of A or B is closest to X</title>
                </interface>
                <audioelement url="1.wav" type="reference" id="or" name="one"/>
                <audioelement url="0.wav" id="z" name="zero"/>
            </page>
            <page id='zeroone2' hostURL="media/example/" repeatCount="2" synchronous="true">
                <commentboxprefix>Comment on fragment</commentboxprefix>
                <interface>
                    <title>Select which of A or B is closest to X</title>
                </interface>
                <audioelement url="0.wav" id="z2" name="zero"/>
                <audioelement url="1.wav" type="reference" id="or2" name="one"/>
            </page>
            <page id='onezero2' hostURL="media/example/" repeatCount="2" synchronous="true">
                <commentboxprefix>Comment on fragment</commentboxprefix>
                <interface>
                    <title>Select which of A or B is closest to X</title>
                </interface>
                <audioelement url="1.wav" id="o2" name="one"/>
                <audioelement url="0.wav" type="reference" id="zr2" name="zero"/>
            </page>
        </waet>

**Comment by nickjillings** [comment]
Complete overhaul of the playback system. Now operates a lot cleaner, separating the buffer playback logic and the user interface logic. Makes it simpler to begin playback of objects regardless of their listen states. In 1e80612
