### ISSUE TITLE
Weird opening dialogue (code/fixed width formatting)

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#242]
A particular test, based on the last master commit, has an odd issue where the first 'survey'/initial message are not wrapping around and in fixed width font. Inspecting the HTML, this text is wrapped in `<pre>` and  `<code>` tags for some reason. See screenshot.

![screen shot 2017-09-20 at 18 46 51](https://user-images.githubusercontent.com/4103243/30656386-44688d78-9e34-11e7-8a2a-a587399063ff.png)

MWE (start of XML): 

<?xml version="1.0" encoding="utf-8"?>
    <waet
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
        <setup interface="APE" projectReturn="save.php" randomiseOrder='true' poolSize="4">
            <survey location="before">
                <surveystatement id="intro">
                    <statement>
                        Thank you for choosing to participate in this experiment.
                        The purpose of your participation is to help us further understand the nature of quality perception in mixes of contemporary popular music. We are hoping to uncover why some music mixes sound better to us than others and whether or not individual mix engineers have a signature style.
                    </statement>
                </surveystatement>
                <surveystatement id="instructions">
                    <statement> 
                        On each page you will hear a number of mixes of a given song and asked to rate them in order of preference. Please take your time to carefully compare the different mixes. Click the different markers to play and toggle between the associated audio, and click 'Stop' to interrupt playback and rewind to the start of the fragments.
                        Click once to play, drag to rate, and comment on the mixes in the corresponding numbered text boxes.
                        When you are ready, please click 'Submit' to finish.
                        The entire test should take about 15 to 20 minutes. 
                    </statement>
                </surveystatement>
            </survey>

**Comment by nickjillings** [comment]
The statement entries are simple nodes. Formatting it like the following will resolve the issue:
```xml
<statement>Thank you for choosing to participate in this experiment.
                    The purpose of your participation is to help us further understand the nature of quality perception in mixes of contemporary popular music. We are hoping to uncover why some music mixes sound better to us than others and whether or not individual mix engineers have a signature style.</statement>
```

**Comment by nickjillings** [comment]
Remove all trailing whitespaces on lines to account for any formatting issues caused by XML indentations.

For code, ensure to use the markdown code markers, tab indented code will be shown as plain text otherwise
