### ISSUE TITLE
Error: You have not completely listened to fragments A and B

### ISSUE THREAD

**Issue by dreamk73** [BrechtDeMan/WebAudioEvaluationTool#246]
Thanks for writing this great code to set up an easy web listening experiment. I just downloaded it and watched the video and started my own test. I have a very simple AB test where I want subjects to listen to each fragment once and decide which one sounds more natural. I thought it would be a good idea to add in a check to make sure they listen to the whole fragment. But if you also select the option to not interrupt the audio, apparently there is some problem. When you listen to both fragments and then select one button and hit submit, you get the error listed in the title. But the fragments have finished playing. And because I set the maximum amount of plays to 1, I can't play them again. 
My solution is to turn off the check and I get the code to work. But I figured you might want to hear about bugs in your code to improve it for the next person to use it.

**Comment by nickjillings** [comment]
Thanks @dreamk73 for submitting this report. The fully played check is an infered check based on start/stop timestamps, so it is perfectly possible these are very slightly within the buffer time causing it to be detected as not fully played.

Can you confirm this was on the master branch and not a release for me, as the master is now significantly ahead of v1.2.2 release zip. Also do you know if this occurs across browsers or was only exhibited in one.

**Comment by dreamk73** [comment]
I got the latest version via git clone. I have only tried it on Google Chrome running on a mac. I can try Safari as well if you think that is helpful.

**Comment by nickjillings** [comment]
So this was caused I think from a similar issue with #249. A minor adjustment has now corrected it. Effectively it was not logging the stopped events, so it did not believe it had played fully.

Tested on Firefox v56 and v57 using the following MWE:
```xml
<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd">
    <setup interface="AB">
        <exitText>Thank you.</exitText>
        <metric>
            <metricenable>testTimer</metricenable>
            <metricenable>elementTimer</metricenable>
            <metricenable>elementListenTracker</metricenable>
        </metric>
        <interface>
            <interfaceoption type="check" name="fragmentFullPlayback" />
        </interface>
    </setup>
    <page id="undefined" label="default" maxNumberPlays="1">
        <commentboxprefix>Comment on track</commentboxprefix>
        <interface/>
        <audioelement url="/media/example/0.wav" id="a" gain="0" />
        <audioelement url="/media/example/1.wav" id="b" gain="0" />
    </page>
</waet>
```
