### ISSUE TITLE
Randomisation not working?

### ISSUE THREAD

**Issue by dreamk73** [BrechtDeMan/WebAudioEvaluationTool#248]
I turned on global randomisation and AB randomisation but when I look at my output xml file, it seems they were all played in order anyway? The presentedID numbers were increasing and always A first, B second?

**Comment by BrechtDeMan** [comment]
There are several kinds of randomisation:

- Random page order, switched on by [setting `randomiseOrder="true"` in the `setup` node](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/XML-specification#setup-setup) or the equivalent check box in the test creator GUI
- Random stimulus order (within a page), switched on by [setting `randomiseOrder="true"` in the `page` node](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/XML-specification#page-page), or the equivalent check box in the test creator GUI
- [Pseudo-random order of tests](https://github.com/BrechtDeMan/WebAudioEvaluationTool/wiki/Pooling-tests) (not applicable here)

Could you confirm whether you have this tag in the `page` node as well, or just in the `setup` node? 
Perhaps this is not what you mean, but I'm getting random order of A and B without any problems.

**Comment by dreamk73** [comment]
I have both page order randomization set to True as well as stimulus order. 

But I did learn from our IT guy that our server runs an old PHP version (5.3.3) so maybe that is why it is not working?

Esther

**Comment by nickjillings** [comment]
The PHP wouldn't have an effect on this particular issue, the randomisation is all done on the client.

I haven't had time to triage this report yet unfortunately, hopefully will get a chance this afternoon otherwise it will possibly be only early next week.

Hopefully it is a minor fix

**Comment by BrechtDeMan** [comment]
Would you mind sending us the input and output XML, or a 'minimal working example' that has this issue for you?

**Comment by dreamk73** [comment]
Sure, here is it.

The way I interpret the saved result is that all pages were played in order and on each page AB order was kept, even though I set randomisation to True on all.

[ab_test.zip](https://github.com/BrechtDeMan/WebAudioEvaluationTool/files/1404711/ab_test.zip)

**Comment by dreamk73** [comment]
Looking at the output file again, maybe it is just my misinterpretation of the results. As I did a longer test, I am now looking at the result file and when I look at the section with the presentedID lists, I see the scores_ field has randomization in the numbers.

**Comment by BrechtDeMan** [comment]
Indeed - you have a 25% chance of getting the ordering '{A-B; A-B}'... 
Do let us know if you have any further problems with this. You can always use the samples in `media/example` to test the structure, if your actual stimuli are hard to distinguish. Until then, I'm closing this issue. Thanks!
