### ISSUE TITLE
Analysis page does not work

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#25]
Depending on PHP version? Browser? 

In Safari, both DMT and QMUL demo does not work: 
DMT: nothing appears when clicking 'Include' radio button
QMUL: 'Test Filenames' don't even appear (though perhaps this is because result XMLs in save don't correspond to any setup XML in test?)

See below for error: 
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (get_tests.php, line 0)
[Error] Error
	(anonymous function) (analysis.js, line 678)

In Chrome, DMT works; QMUL does not. As above, no Test Filenames appear.
Error (on load) below: 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
analysis.js:678 Error: Internal Server Error
    at Error (native)
    at XMLHttpRequest.req.onload (http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/analysis/analysis.js:106:16)(anonymous function) @ analysis.js:678

**Comment by BrechtDeMan** [comment]
Last few lines of the php.log on the QMUL server:

[20-Apr-2016 16:43:15] PHP Parse error:  syntax error, unexpected '[' in /var/www/users/bdm30/mixevaluation1.2/php/get_tests.php on line 39
[20-Apr-2016 16:44:48] PHP Parse error:  syntax error, unexpected '[' in /var/www/users/bdm30/mixevaluation1.2/php/get_tests.php on line 39
[20-Apr-2016 16:45:25] PHP Parse error:  syntax error, unexpected '[' in /var/www/users/bdm30/mixevaluation1.2/php/get_tests.php on line 39

**Comment by nickjillings** [comment]
I'm on PHP Version 5.5.9 so maybe there are some syntax changes. The error seems to suggest that it cannot construct an array object using `[]`. I will look at the other ways to do this.

**Comment by nickjillings** [comment]
This should be fixed now for PHP versions below 5.4.

**Comment by BrechtDeMan** [comment]
Confirmed (it does now appear on this server, for both Chrome and Safari) but the data cannot be loaded:

Chrome
    analysis.js:608 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
        at Object.parse (native)
        at http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/analysis/analysis.js:608:43
    analysis.js:422 Error - Data not loaded

In Safari only the last line is shown (when trying to plot something)

**Comment by giuliomoro** [comment]
this is probably a 404 in disguise (check the console). Incidentally, there are multiple places where the response status is not vaildated  before trying to parse its content

**Comment by BrechtDeMan** [comment]
Hm that would explain it. The above is from the console, no further information. Sure enough that line is where it parses the XML data. 
I've currently got the results in the 'saves' folder, and the configuration XML in 'tests'. Is that not how it should be?

**Comment by nickjillings** [comment]
Here is the HTML page output from your server (http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/php/get_filtered_score.php?url=http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/salford.xml):

FATAL

could not parse file http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/saves/save-h3wuw642cbm83t1ypsgub7k2khvh4r9c.xml:
FATAL

could not parse file http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/saves/save-syauti76ggskow4s4s048kos0skg4scg.xml: { "pages": []}

So of the two pages in your store are not being loaded or parsed correctly.

Check the /saves directory permissions allow the php server to have read-write access (at the minimum read).

**Comment by BrechtDeMan** [comment]
That could be it; no permissions for others. I don't know how to set it on QM servers though (`sudo chmod -R 777 saves/` or something doesn't work). Haven't tried the beautify update either though.

**Comment by nickjillings** [comment]
I think it is more likely that the XML's are presented as one long string with no line breaks. Some libxml distributions have an issue with this. The beautify script will only solve this for future saves, not current ones.

**Comment by BrechtDeMan** [comment]
I can confirm that beautifying the result files as well as the configuration file through http://codebeautify.org/xmlviewer , the analysis page seems to work fine. With the newly created files it seems to work well too. 
On another note, the pound sign ('£') didn't make it through the validation stage of the test. The XML header suggests UTF-8 encoding is used, is this not the case? Is this a bug to log?

**Comment by BrechtDeMan** [comment]
Also loading the data works fine in Google Chrome v50, but doesn't at all in Safari v8.0.4. Pressing the button doesn't seem to have any effect, also no warnings or errors except for our own 'data not loaded' when trying to plot anything. Anyone any luck in Safari?

**Comment by nickjillings** [comment]
It should use UTF-8 encoding, that is the default encoding method unless specifically a larger count is used. I've confirmed the pound does make it into the XML fine when entered. Where did this occur though?

Safari issues are likely similar to #21

**Comment by nickjillings** [comment]
Are there any errors in the console on this? There are no .children operators (removed them all from #21) so it must be a new unique Safari bug (can't replicate here as different versions).

**Comment by nickjillings** [comment]
@BrechtDeMan 

> New error:

[Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.
appendChild (test_core.js, line 1332)
onclick (test_core.js, line 1332)

**Comment by nickjillings** [comment]
Safari does work fine with this. There is a PHP issue on the eecs with invalid XMLs. Cleaning up and removing the invalid XMLs should make this work

**Comment by BrechtDeMan** [comment]
You're right. 

Also no problem with the pound sign ('£') anymore. 

However, I'm getting these warnings in the analysis page: 

[Log] Already a pre/before test survey defined! Ignoring second!! (specification.js, line 115)
[Log] Already a post/after test survey defined! Ignoring second!! (specification.js, line 123)

even though there is only a before/after survey for the full test and also one pre and one post every page. I've seen these warnings a few times and always unwarranted.

**Comment by giuliomoro** [comment]
I thought the pounds symbol was "lbs"

**Comment by nickjillings** [comment]
Yes this was from debugging, I'll fix this now.

**Comment by nickjillings** [comment]
Also, the analysis page cannot cope with switching the test group, it must be refreshed. We do not have any method to clear the on-page Specification (ie, haven't written in destroy and rebuild on test group change).

**Comment by BrechtDeMan** [comment]
> We do not have any method to clear the on-page Specification (ie, haven't written in destroy and rebuild on test group change).

New issue then?
