### ISSUE TITLE
ABX broken

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#256]
On the master branch. 

Only shows A and B (not X), neither of which can be selected: 

    core.js:2387 Uncaught Key X already bounded!

and (upon clicking A or B)

    Uncaught TypeError: Cannot set property 'selected' of null
    at interfaceObject.selectorClicked (ABX.js:237)
    at interfaceObject.handleEvent (ABX.js:259)

See the example project: http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/ABX_example.xml (empty caches if previously accessed)

**Comment by nickjillings** [comment]
Appears to be creating two 'X' elements, and correctly failing the second one from binding a key which stops the execution.

**Comment by nickjillings** [comment]
Potential fix on [hot_fix branch](https://github.com/BrechtDeMan/WebAudioEvaluationTool/tree/hot_fix). Should be able to test by doing
```bash
git checkout hot_fix
git pull origin hot_fix
```

**Comment by BrechtDeMan** [comment]
Yup seems to have fixed it.

**Comment by nickjillings** [comment]
Pulled into master
