### ISSUE TITLE
Use of special characters in text boxes fail

### ISSUE THREAD

**Issue by othiman** [BrechtDeMan/WebAudioEvaluationTool#257]
Hi,

I like to add German text in the survey and the "Test Completed Message" text boxes and therefore use the letters ä, ö, ü and ß in there. The error can be reproduced by creating a new empty MUSHRA test via test_create.html, inserting just an "ä" in the "Test Completed Message" box and clicking the "validate" button. Sometimes it is necessary to click this button twice but then the test fails with the following error message:
```
Your specification is invalid. Please fix the following issues!
    document.xml:1: parser error : Input is not proper UTF-8, indicate encoding !
    Bytes: 0xE4 0x3C 0x2F 0x65
    "0" preSilence="0" postSilence="0" playOne="false" minNumberPlays="0"><exitText>
```

Best regards,
Thomas

**Comment by nickjillings** [comment]
Or use the test create here (already updated) to test.

http://dmtlab.bcu.ac.uk/nickjillings/waet/test_create.html

**Comment by othiman** [comment]
Thanks for the very fast response. The hot_fix is working for me. :-)

**Comment by othiman** [comment]
Just a question about that. Wouldn't it be a good idea to use `<?xml version=\"1.0\" encoding=\"UTF-8\"?>` instead of `<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>` in the fix?
The UTF-8 is at least also working for me and should prevent problems for users in other regions.

**Comment by othiman** [comment]
OK. I had some problems with my browser caching some parts of the listening test site and found out that `<?xml version=\"1.0\" encoding=\"UTF-8\"?>` is not working after all. I think ä, ö, ü and ß are included in UTF-8 so I do not really know why this is not working without the fix.
However, to use the created test xml file with test.html, I needed to fix js/core.js as well (added `<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?> +` in line 252 accordingly).

**Comment by othiman** [comment]
Thanks for the fast help. :-)

**Comment by nickjillings** [comment]
Also, don't be afraid to issue a pull request if you find any issues or fixes!

**Comment by othiman** [comment]
And here is my first pull request: #259. Browser cache prevented me once again from noticing that the export function in test_create was not working any more.

**Comment by othiman** [comment]
@nickjillings, I do not get why this error even did appear. My test.xml file is saved in UTF-8 coding so why does it fail to decode the German umlaute? The solution here is fixing my problem, but what happens if some Chinese user wants to use Mandarin letters in the test?
