### ISSUE TITLE
Test creator XML export problem

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#263]
User has this error when trying to export XML from the test creator. Validation worked no problem. 

```
TypeError: Argument 1 of XMLSerializer.serializeToString is not an object.
Stacktrace:
$s.exportXML@http://localhost/test_create/test_core.js:118:22
fn@http://localhost/js/angular.min.js line 239 > Function:4:144
e@http://localhost/js/angular.min.js:284:187
$eval@http://localhost/js/angular.min.js:148:343
$apply@http://localhost/js/angular.min.js:149:47
compile/</<@http://localhost/js/angular.min.js:284:237
dispatch@http://localhost/js/jquery-2.1.4.js:4434:15
add/elemData.handle@http://localhost/js/jquery-2.1.4.js:4121:6
```

I'm trying to get more background info, but perhaps this rings some bells or raises certain suspicions. 

Different browsers and package as downloaded today.

**Comment by othiman** [comment]
see #257 and #259

**Comment by othiman** [comment]
Regrettably PR #259 mixed with PR #260 somehow. So either someone with the rights has to modify the PR or I have to resubmit it somehow. This github PR splitting is still a mystery for me...

**Comment by othiman** [comment]
OK. I was able to fix PR #259. Now it should just fix the bug described above alone.

**Comment by wil-j-wil** [comment]
Hey guys, I'm getting this bug too. Any advice about ways to get around it?
Cheers,
Will W

**Comment by othiman** [comment]
Hi Will,
have look at pull request #259 (just click on the number). It fixes the problem. Maybe @nickjillings or @BrechtDeMan can have a look at the PR and comment or just apply it that other people do not run into the same problems.

**Comment by nickjillings** [comment]
Hi, sorry I haven't been working on this for a while.

I'll look at your PR now @othiman and merge it in.

**Comment by nickjillings** [comment]
I assume @othiman your two bugs fixes this?

**Comment by othiman** [comment]
For me, it does.
