### ISSUE TITLE
Help - Can't run tests remotely using apache webserver.

### ISSUE THREAD

**Issue by dw-ngcm** [BrechtDeMan/WebAudioEvaluationTool#269]
I can generate tests which work with the python server emulator but they don't work from a web server. I have checked my php install works using a phpinfo script. 

Here is the console log from trying to launch one of the example tests. 

![image](https://user-images.githubusercontent.com/21666210/35226418-26ac3dce-ff83-11e7-9b96-0fba51f53c5a.png)

I'm sorry if there is a blinding error in my setup here, would appreciate any help you can offer. 

Thanks, 

Dan Wallace

**Comment by dw-ngcm** [comment]
![image](https://user-images.githubusercontent.com/21666210/35273170-83519bee-002f-11e8-964d-a00516f731df.png)

Looked though the issues and found your php test implementation - I get failures with the requestKey.php.

**Comment by nickjillings** [comment]
Can you check your logfile on your apache server. It seems like the server fails, which would indicate a permissions issue when running. Check your apache user has read and write access on the saves folder in the WAET root.

**Comment by dw-ngcm** [comment]
Thanks, I'm up and running now. Access permissions were fine (the save test passed). Turns out I hadn't installed php-xml so it was failing to find the simplexml_load_string() function.

**Comment by nickjillings** [comment]
Cool.  Since you are running nit locally, you could just use the python server. That's why we included it!

**Comment by dw-ngcm** [comment]
Indeed, but the analysis tool didn't work with the python server. I wanted to test the full chain - no use getting results which I can't look at!

________________________________

**Comment by nickjillings** [comment]
The analysis scripts probably won't work. They are quite outdated.

**Comment by nickjillings** [comment]
The python scripts do work which will generate boxplots and converting the XMLs to CSV files. They can be used irrespective of whether the python or PHP/Apache server is used.
