### ISSUE TITLE
Disable playing of samples on keypress while in comment boxes 

### ISSUE THREAD

**Issue by dw-ngcm** [BrechtDeMan/WebAudioEvaluationTool#270]
Uncommon issue - more drawing your attention to a quirk. References closed issue #243

When comment boxes have focus, the page still listens for keypresses and plays the corresponding samples. I have an intelligibility test using the mushra (vertical slider) interface where the listener has to type the sentence they hear in the comment box. Some sentences have letters and numbers which precludes using numbers or letters for labels as the samples get triggered by accident while participants are typing.

Workarounds: 
Custom two-character labels for every fragment so they can't be triggered by keyboard.
Commenting out line 2420 in core.js: audioEngineContext.play(this.keys[index].audioObject.id);

**Comment by nickjillings** [comment]
Thanks for posting this! I have confirmed and will fix it now

**Comment by nickjillings** [comment]
Similar fix required to #264

**Comment by nickjillings** [comment]
Fixed in d510923 and pushed to all branches.

If any of the track comment boxes have focus, no key presses will alter the playing (or not playing) fragments.
