### ISSUE TITLE
post-survey dialog should trim the page content so that the scrollbar is deactivated

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#28]
NOTE: may be outdated, I am using an old version (forked around 16bf7d5fa618 of the old hg repo)

Discrete interface
When, e.g.: you have many tracks, so that the scrollbar is active, once you click the "next" button () and the post-survey dialog is displayed, the scrollbar will still be active. The part of the page accessible through the scrollbar is not grayed out.

**Comment by giuliomoro** [comment]
can be fixed setting  div.popupHolder and  div.testHalt to "position: fixed" , although the comments say "do not mess with this bit" ... so maybe this is unsafe?

```` diff
diff -r 49fe2f5efdf8 -r 09326e3d502b core.css
--- a/core.css	Sun Apr 24 20:49:35 2016 +0100
+++ b/core.css	Mon Apr 25 01:17:15 2016 +0100
@@ -42,7 +42,7 @@
 	border-radius: 10px;
 	box-shadow: 0px 0px 50px #000;
 	z-index: 2;
-    position: absolute;
+	position: fixed;
 }

 div#popupContent {
@@ -104,7 +104,7 @@
 	z-index: 2;
 	width: 100%;
 	height: 100%;
-	position: absolute;
+	position: fixed;
 	left: 0px;
 	top: 0px;
 }
diff -r 49fe2f5efdf8 -r 09326e3d502b interfaces/discrete.css
--- a/interfaces/discrete.css	Sun Apr 24 20:49:35 2016 +0100
+++ b/interfaces/discrete.css	Mon Apr 25 01:17:15 2016 +0100
@@ -19,12 +19,12 @@

 div.testHalt {
 	/* Specify any colouring during the test halt for pre/post questions */
	background-color: rgba(0,0,0,0.5);
 	/* Don't mess with this bit */
 	z-index: 2;
 	width: 100%;
 	height: 100%;
-	position: absolute;
+	position: fixed;
 	left: 0px;
 	top: 0px;
 }

**Comment by nickjillings** [comment]
Those are safe, it is more for people trying to customise them on their own to separate colour change from functionality. Have you tested this? If it works, commit and close.

An alternative may be to have all on-page elements inside their own <div> with a scroll, so the page scroll does not show, but this could be cumbersome on mobile devices.
