### ISSUE TITLE
Misalignment of play buttons in Horizontal Interface

### ISSUE THREAD

**Issue by zygurt** [BrechtDeMan/WebAudioEvaluationTool#286]
*Different to Issue #165 
When using the Horizontal Interface, the play buttons do not line up with appropriate track (Vertical misalignment).  They can also only be clicked when not behind the slider's box.
Issue found with Firefox on both Windows and Ubuntu (Firefox v65)
![horizontal interface](https://user-images.githubusercontent.com/5879924/52602250-a3923a00-2ead-11e9-824e-42c7040a480c.png)
.

**Comment by zygurt** [comment]
Not sure if this is the correct way this issue should be solved, but by modifying button.track-slider-button in interfaces/horizontal-sliders.css to
`button.track-slider-button {
    float: inherit;
    width: 100px;
    height: 94px;
    margin-right: -94px;
}`
The buttons appear on the right hand side of the appropriate slider.

**Comment by nickjillings** [comment]
It seems Firefox have changed some CSS markers for things, I've noticed it in other projects as well!

I'll take a look at your fix now

**Comment by nickjillings** [comment]
In the future, please feel free to submit a pull request with your fixes implemented. If they work, we'll just accept!

**Comment by zygurt** [comment]
Too easy.  I'm new to web coding, so I thought it better in this case that someone else adjust the code in a proper' way.  Cheers for the update.

**Comment by nickjillings** [comment]
So I've quickly rewritten the bit which handles the slider objects to use grids. They're a little easier for dynamically sized objects to handle without breaking a pixel here or there!

All fixed!
