### ISSUE TITLE
Test do not run full surveys

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#287]
Currently, on the latest pull, none of the surveys work (Google Chrome)
The first survey question appears, then skips the entire rest of the survey 

This happens with several example tests, including APE, AB and ABX examples.

**Comment by djmoffat** [comment]
I’ve tried debugging this, and in *core.js* it looks like `stateIndex` is triggering `advanceState()` on each `next` click.

I think this is wrong, but I can’t work out how to fix it.

**Comment by zygurt** [comment]
I've also had this issue using Chrome, Firefox and Safari.
I have also tried using the Conditions to force moving between different questions, but this doesn't solve the issue.
Brecht suggested trying an older version during an email conversation.

**Comment by djmoffat** [comment]
@zygurt That is exactly what I have been doing.

@BrechtDeMan perhaps we should roll back the main branch, to that the main branch is always fully working, and put the latest changes back onto a dev branch, if we are not able to build a fix to this.

**Comment by nickjillings** [comment]
OK, I'm looking at this now! To confirm, this is master branch v1.2.3

**Comment by djmoffat** [comment]
@nickjillings Yes, the latest master branch.

I did try to look into rolling back the master branch, and moving the latest push to a separate branch, but I could not work out how to do it. I think I need to learn more git!

**Comment by nickjillings** [comment]
This seems fixed to me now. I'm not sure how that bug got in there but @djmoffat was right, it was incorrectly thinking the state was post survey due to a rogue state movement.

Seems to be working now in Chrome + FF.

**Comment by djmoffat** [comment]
Thanks
—
Dave Moffat
+447969375889
me@davemoffat.com




On 21 Feb 2019, at 11:47, Nick Jillings <notifications@github.com> wrote:

This seems fixed to me now. I'm not sure how that bug got in there but @djmoffat <https://github.com/djmoffat> was right, it was incorrectly thinking the state was post survey due to a rogue state movement.

Seems to be working now in Chrome + FF.

**Comment by nickjillings** [comment]
Should properly test these things, just saw it breaks if no survey elements. Hang on!
