### ISSUE TITLE
Add check for "disable play button while playing"

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#29]
So that, e.g.: in A/B, users will be forced to let the first sample play through before playing the second one.
Useful, e.g.: when you want users to concentrate on the attack part of the note and playing the second one while the first one is playing would affect the perceived effect of the transient.

**Comment by nickjillings** [comment]
Will be easier to have as an option on all interface types. I see the benefits for this, but will need some work to include.

**Comment by nickjillings** [comment]
Adding the attribute `'playOne` to `<setup>` or `<page>` will force the AB to only play one fragment at a time in its entirety.

**Comment by nickjillings** [comment]
I believe this is included now. If I'm mistaken, re-open.
