### ISSUE TITLE
ABX not working

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#32]
the provided tests/examples/ABX_example.xml seems to behave as a regular AB except you cannot make a selection (...)
the console shows this error
````
specification.js:622 Uncaught TypeError: Cannot read property 'schema' of undefined
````

**Comment by giuliomoro** [comment]
also, the provided tests/examples/ABX_example.xml does seem to behave as a regular AB except you cannot make a selection (...)
the console shows this error
````
specification.js:622 Uncaught TypeError: Cannot read property 'schema' of undefined
````

**Comment by nickjillings** [comment]
I believe this is fixed now with your fixes
