### ISSUE TITLE
AB force selection

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#36]
Should provide a way of forcing a selection when using AB/ABX interface

**Comment by giuliomoro** [comment]
Done in 0ec2117 , although there probably are some possible improvements (e.g.: enable/disable the check page wise)

**Comment by nickjillings** [comment]
I'm confused, you can't unselect anything once you have selected one anyway?

**Comment by giuliomoro** [comment]
I am not sure I get your question right. You surely can select/unselect things, but some times you would want to make sure that the user has made a selection before they click submit. This is what I addressed in 4d386acc1d426125e69604b7ee37e3df3d2d368f then in 0ec21175777ef36cdcb7d128eeb414e38ea8549e I disabled such check when there is at least one "inactive" element. As mentioned, this could be improved by enabling/disabling the check page-wise

**Comment by giuliomoro** [comment]
Oh I see: do you mean that people can unselect previously selected selections and this would still pass my check?
Yes you are right. So I guess this outlines another bug.

**Comment by nickjillings** [comment]
No I mean once one of the options has been selected, you have a choice: select the same one or select a different one. There is no way to deselect and have nothing selected once at least one has been selected in the first place.

**Comment by giuliomoro** [comment]
Which, in my opinion, it is a severe bug, see #42

**Comment by giuliomoro** [comment]
And anyhow the point here is to force that at least one of the two elements is selected (maybe it is the same as "check slider moved" , but did not work for AB)

**Comment by nickjillings** [comment]
OK, right now it seems you can deselect AB or ABX once selected. So we can either: you cannot deselect and go back to none selected or allow you to have none-selected at any stage.

**Comment by nickjillings** [comment]
Answering that will determine #42

**Comment by giuliomoro** [comment]
I would say we need a
`<interfaceoption type="check" name="oneFragmentSelected" />`
to make sure that (if needed), the user is forced to pick at one selection. If the check is not enabled, then the user is free not to pick any choice.

In the GUI this should translate into:
1) you are allowed at any time to unselect a previously selected item. This should be reflected in the stored "selected" state (which is currently not done and which is #42).
2) if the check is enabled, you have to have one item selected at the moment when you click submit

Does it sound like a reasonable design?

If it does, 2) is already implemented in 4d386acc1d426125e69604b7ee37e3df3d2d368f , but will only work if 1)(#42) is fixed

**Comment by nickjillings** [comment]
Yes that makes sense, although the check:
`<interfaceoption type="check" name="scalerange" min="25" max="75"/>`
would do the same as it will make sure that at least one is above 0.75 (since we operate normalised floats) and another is unselected (which would always be necessary).

I'll fix #42 now

**Comment by giuliomoro** [comment]
It looks like scalerange is not working in AB. New issue #43

**Comment by nickjillings** [comment]
Yes, this is actually across the entire test platform and needs to be implemented. APE has it because it needs a custom method to handle multiple axis.
