### ISSUE TITLE
Beautify-script

### ISSUE THREAD

**Issue by nickjillings** [BrechtDeMan/WebAudioEvaluationTool#46]
PHP & Python servers should beautify files for transfer for further edits by text-editors. Mostly for XML but possible for JSON transfers as well.

CSV already has through new-line delineation.

**Comment by giuliomoro** [comment]
As a +1, also note that xmls with too-long-lines fail parsing on some PHP servers.

**Comment by nickjillings** [comment]
True, this could be what is causing the problems with #25

**Comment by nickjillings** [comment]
PHP server will now beautify all future saves, python server not yet (need to look how to do that automatically).

**Comment by giuliomoro** [comment]
huge!

**Comment by giuliomoro** [comment]
Should be applied also to test_create.html !

**Comment by nickjillings** [comment]
In what way? The returned, filtered XML?
