### ISSUE TITLE
Archive saves

### ISSUE THREAD

**Issue by nickjillings** [BrechtDeMan/WebAudioEvaluationTool#47]
PHP/Python scripts to automatically package up all XMLs on a page and transmit them as a zip or other compressed format for quick transfer

**Comment by nickjillings** [comment]
From a security point of view, we need to decide whether this is actually a useful thing to do. Especially since it would mean a third party could investigate on the server and the remove / copy all the raw data files.

@BrechtDeMan @djmoffat @giuliomoro any thoughts?

**Comment by djmoffat** [comment]
I think it would be a useful functionality, but not priority

**Comment by nickjillings** [comment]
I'm still not sure on how to do this securely. I'm against the ability to interrogate the server and potentially steal a whole set of test results in one swift PHP script. I think if people have been able to set up the server, they have access to it themselves and therefore can get the files back.

**Comment by BrechtDeMan** [comment]
I agree about erring on the side of security. Most of the time you'd have access to the server anyway (ssh, ...)
