### ISSUE TITLE
Is Javascript code in index.html supposed to stay there?

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#48]
It looks just like an old duplicated of what is in test.html

**Comment by BrechtDeMan** [comment]
That's right - the idea is that you can append '?url=tests/hammondattacks.xml' there as well. It's not strictly necessary. It's a judgement call we made during a meeting a week or two ago. 
Do you think it's in the way?

**Comment by giuliomoro** [comment]
There are multiple lines of duplicated code between test.html and index.html, this is to be avoided.I'd say they should be packaged up in a different file and included in there, shouldn't they?

**Comment by nickjillings** [comment]
It used to be a hangover from when the scripts were dragged in or loaded directly by modifying the index.html. It's in the core.js now.
