### ISSUE TITLE
Autosaves and final save continuously replace the same file

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#49]
if I am not mistaken, we are overwriting the same file at every save attempt. This potentially will cause data loss, e.g.: if a server error occurs while writing to the file, or you run out of space. I guess a better way to do this would be to either save intermediate saves with incremental numbers and delete the intermediate files after a successful final save, or to create a backup of the file before overwriting it and deleting it if the new file was create successfully.

**Comment by nickjillings** [comment]
In dev_main (vnext) branches (e7edbb5)

**Comment by nickjillings** [comment]
Each file is now opened and compared against the incomming XML and updates any nodes which need updating. It only checks the node's "state" value and replaces if `state != "complete"`. Rudimentary but should suffice in ensuring files are updated rather than overwritten.
