### ISSUE TITLE
Analysis page: axis labels and titles

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#54]
Y-axis could be the axis label (e.g. for APE interfaces at least) or otherwise 'Rating'; x-label could be 'Audio element'. 

More importantly though, when getting an error like 'Not enough columns given to draw the requested chart.', the title should be displayed as well so you know where the 'problem' is.

**Comment by djmoffat** [comment]
I feel that this is very low priority - as discussed, we should only be focusing on bug fixes, and not analysis, other than very easy analysis.

**Comment by nickjillings** [comment]
Is this fixed though? If it is not, best to keep it open as it will be a future issue that needs fixing.
