### ISSUE TITLE
replacing alert() with lightbox

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#55]
We should find a drop-in replacement for alert() that uses a lightbox instead and then 
````bash
find waet/ -name *.js -exec sed -i '' 's/alert(/lightAlert(/g' {} \;
````

**Comment by nickjillings** [comment]
Agreed, the on-page popup could probably work just as well.

**Comment by giuliomoro** [comment]
yes, that sort of thing :)
