### ISSUE TITLE
querystring parameters for test.html

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#56]
To elaborate on #50 I would suggest the following additions to the querystring to test.html.
Both options could be defaulted in the xml, but should be overridden via the querystring

* returnUrl=  ... url to go with `window.location = returnURL;` once the output is saved. If no returnUrl is passed or it is empty, then the test should end with the save-confirmation dialog. Current bug makes the test restart once it is done ( see #50)

* saveFilenamePrefix= ... this will be passed to save.php. This would, e.g.: allow to keep track of a given user through a wrapper which combines multiple tests together.

in js/core.js:
````js
               var saveUrl = "php/"+destURL+"?key="
                    +storage.SessionKey.key+'&saveFilenamePrefix='+saveFilenamePrefix;
               xmlhttp.open("POST", saveUrl, true);
````
save.php would then need to be patched:
````diff
        error_reporting(0);
+       $saveFilenamePrefix = isset($_GET['saveFilenamePrefix']) ? $_GET['saveFilenamePrefix'].'-' : '';
        header('Access-Control-Allow-Origin: *');
        header("Content-type: text/xml");
        $postText = file_get_contents('php://input');
        $file_key = $_GET['key'];
-    $filename = "../saves/save-".$file_key.".xml";
+       $filename = '../saves/'.$saveFilenamePrefix.'save-'.$file_key.".xml";
     $doc = new DOMDocument;
     $doc->preserveWhiteSpace = false;
     $doc->formatOutput = true;
````

**Comment by nickjillings** [comment]
ReturnURL can be modified from the URL, for instance `index.html?url=tests/examples/project.xml&projectReturn=http://google.co.uk/`

Can you expand on the second point? Each file is a unique user so it is possible to track a session anyway. It may be just as simple as renaming the file once completed to reach this rather than adding more to the URL. Adds danger from refreshing and caching URLs which will break this principle.

**Comment by giuliomoro** [comment]
reason why I want saveFilenamePrefix is so that you can five a URL to a person with an appropriate saveFilenamePrefix and later be able to tell which saved file was generated from that URL.

In my case, I have a page that wraps multiple tests and I am using saveFilenamePrefix to keep track of a given user across tests.
