### ISSUE TITLE
APE poolsize broken

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#58]
poolsize="2" gives 4 pages, and so on. 

Might be related to the 'repeated pages' bug (#59)

Happens in Safari as well as in Chrome.

**Comment by nickjillings** [comment]
Do any of the pages have a repeatCount > 0?

**Comment by nickjillings** [comment]
I can't replicate any of these issues (also repeatCount is broken anyway for the pooling of pages). It could be another Safari v8.0.4 bug causing problems.

Does this crop-up in all browsers?

**Comment by BrechtDeMan** [comment]
Used to be all browsers yes. Seems to be working now with latest commits though. Thanks!
