### ISSUE TITLE
Repeated pages selected from pool

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#59]
I.e. the same page occurs twice when four pages are selected from a pool of [18] different pages. 

Possibly related to #58: 'poolsize' has to be half the desired number of pages, so perhaps two pages from the pool twice, instead of four once, which could lead to repetition.

**Comment by nickjillings** [comment]
Are any of those pages with a repeatCount > 0

**Comment by BrechtDeMan** [comment]
No

**Comment by nickjillings** [comment]
Can you check that this is still an issue as it may have been cleared up since #58 was closed.

**Comment by BrechtDeMan** [comment]
Oh yeah this is fixed as well.
