### ISSUE TITLE
Fix comment questions on AB test

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#61]
Following user's comment that 'comment questions' are not visible on AB style tests.

**Comment by djmoffat** [comment]
Comments are working however comment questions without comment boxes are not working.

**Comment by djmoffat** [comment]
AB.js:210 Uncaught TypeError: Cannot read property 'appendChild' of undefined(anonymous function) @ AB.js:210each @ jquery-2.1.4.js:374each @ jquery-2.1.4.js:139loadTest @ AB.js:208Interface.newPage @ core.js:1985advanceState @ core.js:1134advanceState @ core.js:1084advanceState @ core.js:1073loadInterface @ AB.js:123(anonymous function) @ AB.js:2

**Comment by djmoffat** [comment]
When a second AB test appears, with comment question - a second comment question box appears and the submit button disappears.

**Comment by nickjillings** [comment]
Confirmed this

**Comment by nickjillings** [comment]
Ah, seems if you do 'Fixed ....' it closes it automatically now... Will watch that! Re-open if it's still not actually fixed

**Comment by djmoffat** [comment]
That's quite clever!
Tested and it all seems fine.
