### ISSUE TITLE
Remove hook for pressing enter-> 

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#64]
This is annoying especially when using a huge or large textbox where you would expect people to write longer texts but they cannot break lines.

I would suggest removing the hooks for all the textboxes. After all, people would not be bothered to  click "next". If we want to keep a shortcut for ourselves when testing the tests/surveys, then let's replace the hook on "enter" with a hook on "shift+enter"

This would do it
````diff
--- a/js/core.js
+++ b/js/core.js
@@ -618,7 +618,7 @@ function interfacePopup() {
        this.node = null;
        this.store = null;
        $(window).keypress(function(e){
-                       if (e.keyCode == 13 && popup.popup.style.visibility == 'visible')
+                       if (e.keyCode == 13 && e.shiftKey === true && popup.popup.style.visibility == 'visible')
                        {
                                console.log(e);
                                popup.buttonProceed.onclick();
````

**Comment by giuliomoro** [comment]
this is a design change, so I pushed it to my branch 4d72ac

**Comment by BrechtDeMan** [comment]
To be clear: your suggestion is that "enter" ALWAYS inserts a new line, and "shift + enter" submits the question? 

We've had a few discussions about desired behaviour of the survey questions. I personally feel quite strongly about a simple "enter" moving to the next question, as that is the behaviour participants seem to expect (Name: 'John Smith' *enter*). 
"shift+enter" should create a new line then. 
This is something different developers seem to do differently, sometimes within the same app, and it can be annoying. There is also no clear right or wrong. 
Happy to discuss further.

**Comment by giuliomoro** [comment]
When the question expects a long answer, e.g.: "Do you play any instruments? How long have you played them? What is your main instrument?", you surely want people to be able to (somehow) format it using newlines. Now, it is much more likely that they will be capable of creating newlines if that is done through an "enter", while way less people will be familiar with shift+enter.
Having to "click" on the "next" button a few times is not a big deal for who takes the test. Surely that is annoying for us when developing/testing it.
I would go for one of two solutions:- always bind enter to newline and shift+enter to "next" (as I did in 24d72ac61c59496d824466116608aa96b3257c10 )- bind enter to newline only when there is a large textbox.  Or better, create a new type of textbox (one-line) as the only textbox where enter is bound to "next". This would mimic the behaviour of most forms, where input="text" is one line which does not take the focus away from the "submit" button, while textarea does

**Comment by BrechtDeMan** [comment]
The latter option sounds agreeable to me. In that case, though, the 'Next' button should be clearly 'selected' (in focus) whenever enter would proceed to the next question. 
Perhaps the 'ghost text' in the text box could tell the subjects that Enter creates a newline and Shift+Enter proceeds to the next question. 
Let's decide on a rule and implement it everywhere once and for all - no functionality/configuration visible to the user.

**Comment by nickjillings** [comment]
Perhaps for the small text boxes, where it is one line, pressing enter should progress. Otherwise the enter key should insert a new line. For radio/checkbox/number it should also have the current behaviour. Does that work better?

**Comment by BrechtDeMan** [comment]
Works great for me, yes. 

I didn't realise there was no way to do a new line at this point, definitely needs to change. And perhaps a simple 'Enter' works best - but I would request that the 'Next' button gets 'selected' when it is in focus, so that the difference in behaviour is visually obvious.

**Comment by nickjillings** [comment]
It is a tricky one with focus, you can't bind the keyboard focus twice. For instance when the text entry box appears we give that focus so users can immediately begin typing into the box. But we steal the enter keys and bind them into the click function on the button. Therefore it is difficult to show to the user both ways, that pressing enter will move it forward or not. Likewise if you have the list of radios/checkboxes, pressing tab should 'scroll' through giving focus to each entry, but we steal the enter which would normally (un)check the entry.

I'm not sure if there is a clean way to support both enter key bindings and newline without breaking some form of UI expectation.

Perhaps we should make shift+enter the shortcut for moving forward (for us developer hacky lot). If the user tabs through to the next button and presses enter, the same behaviour will continue.

**Comment by BrechtDeMan** [comment]
Right, gotcha. I was thinking the outline of the button could be a thick black line so that it looks 'selected', whenever the survey question type is NOT 'large question box'. 

I didn't know about tabbing through options. Sounds useful. Could you not make 'space' the checkbox/radio button (un)selector?

**Comment by nickjillings** [comment]
It's about having a consistent UI that users would expect. The button should highlight when the focus is on it anyway. However when typing into a box that has focus, so perhaps we should not have enter ever be stolen in the popup window.

If the button has focus, then it will show it on browsers and the enter key will behave as normal.
