### ISSUE TITLE
intermediate saving can be slow ...

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#65]
... and slow down your server ... unless your server is already slow enough ...
is there no more clever way of saving intermediate steps?
at the moment we are rewriting the file every time, which makes write operations increasingly slower as the tests proceeds ... 
Also see #49 regarding the (un)safeness of the current approach which truncates the existing file at each new write

I am not sure which would be the best way to address these ... maybe leave the  `<waetresult>` tag open after the first intermediate save and only append the most recent `<page>` element at each incremental save ?
This reduces a) system load b) network usage c) risk of corruption

**Comment by nickjillings** [comment]
Closed as effectively the same as #49. Or more accurately, both have the same solution. I want to perform the saves better anyway.
