### ISSUE TITLE
Test creator doesn't load on Safari 8.0.4

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#70]
Going to http://localhost:8000/test_create.html on Safari v8.0.4 doesn't load anything, and gives this error

[Error] TypeError: undefined is not an object (evaluating 'this.testsXML.length')
	(anonymous function) (test_core.js, line 282)
	(anonymous function) (test_core.js, line 307)
	buildPage (test_core.js, line 1100)
	onload (test_core.js, line 96)

If many issues are just Safari v8 we may have to abandon legacy versions of Safari... So it would be useful if others could confirm.

**Comment by BrechtDeMan** [comment]
Same on an actual webserver (which works on Chrome) http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation/test_create.html

**Comment by nickjillings** [comment]
Most likely related to #21

**Comment by nickjillings** [comment]
Can you check if the above fix works (dev_main)

**Comment by BrechtDeMan** [comment]
Yup, thanks

**Comment by BrechtDeMan** [comment]
Actually, I get this on submitting, in Safari v8 (related to #21?): 

[Error] TypeError: undefined is not an object (evaluating 'RootDocument.children[0]')
	encode (specification.js, line 166)
	onclick (test_core.js, line 1323)

**Comment by nickjillings** [comment]
Yeah all those ones where it says error of .children is the same bug as #21. I'm amazed it hasn't cropped up before. I will change it now. The children[0] are quite easy as it is the same as .firstElementChild.,

**Comment by nickjillings** [comment]
Fixed now (on master as a hotfix)

**Comment by BrechtDeMan** [comment]
New error: 

[Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.
	appendChild (test_core.js, line 1332)
	onclick (test_core.js, line 1332)

**Comment by nickjillings** [comment]
@BrechtDeMan can you check if the minor correction in dev_main has solved it?

**Comment by BrechtDeMan** [comment]
I now get the Save dialog when clicking 'export XML', but it doesn't save/download. 
Testing this on localhost (pythonServer) by the way. 

<img width="420" alt="screen shot 2016-05-27 at 11 45 44" src="https://cloud.githubusercontent.com/assets/4103243/15604447/b6a4bf92-2400-11e6-8ff1-dd21d6a0a712.png">

**Comment by nickjillings** [comment]
You have to right click on the save link. Safari doesn't support the HTML5 clicking to download (really annoying) from inside a page

**Comment by BrechtDeMan** [comment]
That's what I did though ('Download link (as ...)'). Interestingly when I do click it I see the XML in the browser window as usual with Safari. So the XML is produced, it just cannot save it somehow... 

The link if I copy it is `blob:http://localhost:8000/8286fddb-e6ce-4e28-8e3e-731c937252c6 `

**Comment by nickjillings** [comment]
OK, when you click on it and do File -> Save As... you can save the XML that way.

Here is the problem: [http://caniuse.com/#feat=download](http://caniuse.com/#feat=download). Safari and Edge do not support the download tag. The only way to dynamically trigger a download is through using a header (which we don't do as no server paradigm, plus hacky to send it back to server then re-download and wasteful).

**Comment by nickjillings** [comment]
Added in an explanation on how to save with Safari. Possibly could do some browser detection to only show this message to safari users but the rest of this bug is out of our hands.

**Comment by BrechtDeMan** [comment]
In that case it insists on saving it as a .webarchive: 

`bplist00Ñ_WebMainResourceÕ	
_WebResourceFrameName^WebResourceURL_WebResourceData_WebResourceMIMEType_WebResourceTextEncodingNameP_?blob:http://localhost:8000/91b1d646-c91c-49aa-906e-57ba450c80ccO.à<html xmlns="http://www.w3.org/1999/xhtml"><head><style id="xml-viewer-style">body{margin:0}div.header{border-bottom:2px solid black;padding-bottom:5px;margin:10px}div.collapsible&gt;div.hidden{display:none}.pretty-print{margin-top:1em;margin-left:20px;font-family:monospace;font-size:13px}.collapsible-content{margin-left:1em}.comment{color:rgb(35,110,37);white-space:pre}.tag{color:rgb(136,18,128)}.attribute-name{color:rgb(153,69,0)}.attribute-value{color:rgb(26,26,166)}.button{-webkit-user-select:none;cursor:pointer;display:inline-block;margin-left:-10px;width:10px;background-repeat:no-repeat;background-position:left top;vertical-align:bottom}.collapse-button{background-image:-webkit-canvas(arrowDown);height:10px}.expand-button{background-image:-webkit-canvas(arrowRight);height:11px}</style></head><body><div class="header"><span>This XML file does not appear to have any style information associated with it. The document tree is shown below.</span><br /></div><div class="pretty-print" id="tree"><div class="collapsible" id="collapsible0"><div class="expanded"><div class="line"><span class="button collapse-button"></span><span class="tag">&lt;waet<span> <span class="attribute-name">xmlns:xsi</span>="<span class="attribute-value">http://www.w3.org/2001/XMLSchema-instance</span>"</span> [AND SO ON ...] </body></html>_application/xmlUUTF-8`
