### ISSUE TITLE
test_create does not create comment boxes

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#71]
No comment boxes appear, despite being explicitly requested in the general interface settings and one of the page interface settings. 

APE interface, viewed in Google Chrome v50.0. 

Attached: [PDF printout of test-create](https://github.com/BrechtDeMan/WebAudioEvaluationTool/files/267835/test_create-test.pdf)

XML: 
`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="APE" returnURL="http://www.youtube.com" randomiseOrder="true" loudness="-23" crossFade="0.1"><exitText>Thank you for being a nice person.</exitText><survey location="pre"><surveyentry type="question" id="subjectname" mandatory="true" boxsize="normal"><statement>Name:</statement></surveyentry><surveyentry type="number" id="age" min="1" max="120"><statement>Age:</statement></surveyentry><surveyentry type="radio" id="occupation"><statement>Occupation</statement><option name="student">Student</option><option name="not a student">Not a student</option></surveyentry></survey><survey location="post"><surveyentry type="checkbox" id="feelings"><statement>How did you feel when performing the test?</statement><option name="happy">Happy</option><option name="sad">Sad</option><option name="angry">Angry</option><option name="confused">Confused</option></surveyentry></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"><interfaceoption type="check" name="fragmentMoved"></interfaceoption><interfaceoption type="check" name="fragmentPlayed"></interfaceoption><interfaceoption type="check" name="fragmentComments"></interfaceoption><interfaceoption type="show" name="comments"></interfaceoption><interfaceoption type="show" name="volume"></interfaceoption><interfaceoption type="show" name="page-count"></interfaceoption></interface></setup><page id="counting" hostURL="media/example/" randomiseOrder="true"><commentboxprefix>Comment on fragment</commentboxprefix><interface name="null"><title>Depth</title><scales><scalelabel position="0">Bad</scalelabel><scalelabel position="25">Poor</scalelabel><scalelabel position="50">Fair</scalelabel><scalelabel position="75">Good</scalelabel><scalelabel position="100">Excellent</scalelabel></scales></interface><interface name="null"><title>Width</title><scales><scalelabel position="0">this is zero</scalelabel><scalelabel position="100">this is one hundred</scalelabel><scalelabel position="17">favourite number</scalelabel></scales></interface><audioelement id="_0" url="0.wav" gain="0" name="a_zero"></audioelement><audioelement id="_1" url="1.wav" gain="-12" name="a_one" preSilence="1"></audioelement><survey location="pre"></survey><survey location="post"><surveyentry type="question" id="ease" boxsize="large"><statement>How did you feel? </statement></surveyentry></survey></page><page id="more_counting" hostURL="media/example/" randomiseOrder="true" loop="true"><commentboxprefix>Comment on audio clip</commentboxprefix><interface name="null"><title>Any attribute</title><interfaceoption type="check" name="scalerange"></interfaceoption><interfaceoption type="show" name="page-count"></interfaceoption><interfaceoption type="show" name="playhead"></interfaceoption><scales><scalelabel position="0">Strongly Disagree - no! </scalelabel><scalelabel position="25">Disagree</scalelabel><scalelabel position="50">Neutral</scalelabel><scalelabel position="75">Agree</scalelabel><scalelabel position="100">Strongly Agree - yay!</scalelabel></scales></interface><audioelement id="_2" url="2.wav" gain="0" name="b_two"></audioelement><audioelement id="_3" url="3.wav" gain="0" name="b_three"></audioelement><audioelement id="_4" url="4.wav" gain="0" name="four" type="reference"></audioelement><audioelement id="_4ref" url="4.wav" gain="0" name="four" type="outside-reference"></audioelement><survey location="pre"><surveyentry type="statement" id="examplestatement"><statement>This is a 'before survey' question.</statement></surveyentry></survey><survey location="post"></survey></page></waet>`

**Comment by nickjillings** [comment]
Which browser was this specification made in? Chrome or Safari

**Comment by BrechtDeMan** [comment]
Chrome, as test_create.html doesn't work at all for me in Safari (#70).

**Comment by nickjillings** [comment]
I can't replicate this in Chrome, it works for me. Did you check the show element comments in the page? When I loaded in your XML above and checked it for the page the export had `howElementComments="true"`

**Comment by BrechtDeMan** [comment]
Tested in both Safari v8 and Chrome v50 with 'show element comments' checked in the general options, AND checked in one of the two pages. 

For the other page, I did not check that checkbox - apparently it overrides the general one? In this case what's the use of it? 

Even though there are no text boxes at all in the test, the tags are present in the XML, see below. 

The documentation needs updating (or the test_create has errors), as it says

> showElementComments: Boolean, optional. If true then there will be a comment box on the test page for each audio element presented, see Section 6.11.

`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="APE"><exitText>Thank you.</exitText><survey location="pre"></survey><survey location="post"></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"><interfaceoption type="show" name="comments"></interfaceoption></interface></setup><page id="depth" hostURL="media/example/"><commentboxprefix>Comment on track</commentboxprefix><interface name="null"><title>Depth</title></interface><audioelement id="zero" url="0.wav" gain="0"></audioelement><audioelement id="one" url="1.wav" gain="0"></audioelement><survey location="pre"></survey><survey location="post"></survey></page><page id="height" hostURL="media/example/"><commentboxprefix>Comment on track</commentboxprefix><interface name="null"><title>Height</title><interfaceoption type="show" name="comments"></interfaceoption></interface><audioelement id="two" url="2.wav" gain="0"></audioelement><audioelement id="three" url="3.wav" gain="0"></audioelement><survey location="pre"></survey><survey location="post"></survey></page></waet>`

**Comment by nickjillings** [comment]
It seems that somewhere two comment box options have been created. If you look in the top of the page attributes list there is a show comment boxes there which generates the page `showElementComments` boolean. In this case the comment boxes are not shown because the pages look for the showElementComments tag not the new `<interfaceoption type="show" name="comments"/>` node.

**Comment by nickjillings** [comment]
This should be fixed now

**Comment by BrechtDeMan** [comment]
Confirmed.
