### ISSUE TITLE
test_create: sample rate defaults to 0

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#72]
Leaving the test-wide 'sample rate' field blank leads to the attribute 'sampleRate="0"'. The desired behaviour is that it is simply not present, and as such does not require any specific sample rate from the user (i.e. resampled automatically). 

Attached: [PDF printout of test-create](https://github.com/BrechtDeMan/WebAudioEvaluationTool/files/267835/test_create-test.pdf)

**Comment by nickjillings** [comment]
Is this definitely on the latest / recent version? The specification.js a while back changed the default of the sampleRate from "0" to undefined a long time ago

**Comment by BrechtDeMan** [comment]
Tested again and the issue is actually slightly more subtle: if you enter something in the sample rate field, and then empty it again, there is going to be a 'sampleRate="0"' attribute.

**Comment by nickjillings** [comment]
Nice spot! Fixed now
