### ISSUE TITLE
test_create: Extra 'Add Marker' buttons in Edit Scale Markers window 

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#73]
See below. One will do! 

It would seem a new one is added every time this type of window is opened (even across different pages). 

<img width="808" alt="5 add marker buttons" src="https://cloud.githubusercontent.com/assets/4103243/15318118/7f8aa026-1c1c-11e6-8db2-de02e9ffe333.png">

**Comment by nickjillings** [comment]
Fixed in Dev_main (d036679)
