### ISSUE TITLE
test_create: 'Likert' default drop down menu selection

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#75]
- ~~In Interface markers, ‘Likert’ is the default drop down menu selection, but you have to go to another interface and then back to Likert to make it~~
- Similarly, when going out of this Interface markers menu and back to it, the markers are preserved but ‘Likert’ is selected in this menu again. It should remember what choice was made, or if other markers were selected, the drop down menu value could automatically jump to ‘Custom’ maybe. 
  <img width="640" alt="screen shot 2016-05-16 at 22 07 00" src="https://cloud.githubusercontent.com/assets/4103243/15318872/ff50de30-1c1f-11e6-9a95-7e46e5c58f54.png">

**Comment by BrechtDeMan** [comment]
Implemented first bullet point (review please), see commit 88ce9d9b27c759e4b9fa0e3a981b563976ad3d15 

Now just 'remembering the position of the drop down menu' needs to be implemented, as well as jumping to 'custom' when deviating from the preset, or whatever is the most sensible.

**Comment by nickjillings** [comment]
Having reviewed this now ancient issue, I think it is acceptable to leave it as it is for now. The whole test_create needs reworking. So I'll pull it out of 1.2.1 becuase it does work. However there are neater ways to do this, but reworking will take too long right now (perhaps 1.2.2).

**Comment by nickjillings** [comment]
Implemented in v1.2.2
