### ISSUE TITLE
test_create entry format checking and instructions

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#76]
Without overengineering it (we can give the user some credit), some basic checking and/or instructions would be useful, e.g.:
- check/specify that any xs:ID field should be unique and starting with a letter or underscore etc.
- Loudness: constrain to ... - 0 LU? 
- 'Pool size' and 'Save Return URL' - add instructions (next to text box, or inside text box as placeholder text)
- 'Randomise order' checked by default (not sure how to set defaults)
- ...

**Comment by nickjillings** [comment]
Moved to v.next as easier to address once entire test_create model is tackled

**Comment by nickjillings** [comment]
So all these should now be fixed in the Dev_main
