### ISSUE TITLE
Wrap around text of long axis labels on left side

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#77]
Potentially problematic markers on left side: goes out of the window if it's a long label. 
Right side is fine. 

<img width="1465" alt="screen shot 2016-05-16 at 22 55 15" src="https://cloud.githubusercontent.com/assets/4103243/15320082/98923dae-1c26-11e6-9dd2-1dfb73a2de04.png">

Desired behaviour? New line such that it fits in the window? 

Proposal: 'Text box' width of marker label should be the distance between that marker and the closest marker to it, OR twice the , whichever is smaller. That way, there is no overlap with text or the end of the window, centring around the specified value can be preserved, and the 'text box' is maximally wide such that most labels will only take up a single line. 

Perhaps there is a simpler, more common approach.

**Comment by nickjillings** [comment]
Should be fixed in a6d1587e6c
