### ISSUE TITLE
Optional 'tick marks' on scales

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#78]
Option to show a 'tick mark' (small line indicating the exact position of a label). 

Specifically for APE; MUSHRA already has it and it's irrelevant for e.g. AB.

**Comment by nickjillings** [comment]
Easier to either say 'optional for all interfaces' or 'always on/off'

**Comment by BrechtDeMan** [comment]
Sure, I'd personally go with optional for all interfaces. Perhaps 'off' can be the default, but I don't feel very strongly about it. It's yet another option though so should be presented (/tucked away) neatly. 
Not urgent.

**Comment by nickjillings** [comment]
The only neat way I can see to do this is to create an `interfaceoption` tag:
```xml
<interfaceoption type="show" name="ticks" />
```
