### ISSUE TITLE
test_create: make questions draggable to change order

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#79]
It would be nice if I could drag the order of questions after creating them (and perhaps pages, audio elements, though that’s not meaningful if there is randomisation and might overcomplicate things). For questions it would seem to make sense e.g. when an existing XML is modified, or when you forget the first question and you don’t want to delete everything and add it again…

**Comment by nickjillings** [comment]
Implemented in master as of 41b3148ca.

No dragging as that is very complex but uses buttons to move up/down the elements
