### ISSUE TITLE
Internet Explorer 11 not working

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#80]
all I know is below:
<img width="543" alt="screen shot 2016-05-17 at 16 16 21" src="https://cloud.githubusercontent.com/assets/4260604/15327944/2043de6e-1c4b-11e6-850a-25e6724b5d1a.png">

[pre_survey.xml.zip](https://github.com/BrechtDeMan/WebAudioEvaluationTool/files/268534/pre_survey.xml.zip)

**Comment by giuliomoro** [comment]
comment from the same person:

> Opened on Chrome, told me it required Flash which is already installed on this computer. Then it tried to install some kind of HD video player which I blocked, sorry don't need another program installed.

**Comment by nickjillings** [comment]
On first comment, that sounds like they are using the 1.1.0 which is still available on the sound software site. That had the index.html only show Web Audio Evaluation Toolbox.

On the second one, seems more likely to be a re-routing caused on there end as we have zero to do with Flash.

**Comment by nickjillings** [comment]
On that, it will never work for Internet Explorer as they don't support web audio. Web audio API was only introduced on Edge (IE 12+)

**Comment by giuliomoro** [comment]
They were actually trying to take my test so the software revision i maybe ten days older at most

**Comment by nickjillings** [comment]
What is your test URL can you email it to me. There may be some more nefarious routing going on then for the second one.

On the first, either way IE 11 is not supported, only Edge or newer (and it is untested, I will get a debug list tonight once on my windows machine)

**Comment by nickjillings** [comment]
FYI #90. Edge now works

**Comment by nickjillings** [comment]
Just checked on Internet Explorer 11 (still submitted with windows 10 despite edge).

Turns out it fails because it cannot parse the JavaScript formats used. These are all written using the new ECMA5, however IE11 doesn't even support some of the functions in that now deprecated standard.

May create a new dynamic loading system which will only load files IF the test can run.

**Comment by nickjillings** [comment]
Closed with #81 #90 and #91
