### ISSUE TITLE
Short, accidental 'drags' converted to clicks

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#82]
How about this: I quite often accidentally drag a slider for a millimetre of so instead of clicking it, specifically when I move to the slider from somewhere else on the screen, and then click it while still moving a tiny little bit. 
It makes the interface feel a little buggy and unreliable, even if it's really my own 'mistake'. Could a very short drag like that _also_ toggle playback on this sample? 

Specific to APE.

**Comment by giuliomoro** [comment]
Is this the issue Adib was experiencing?

**Comment by nickjillings** [comment]
No that was an error I have now fixed where the track indexes did not match up with their position in the APE metric tracker. If the outside reference was randomised so it was somewhere in the middle of the array, the trackers would fail as the metric list does not include the outside reference, as it is not part of the slider group (if that makes sense). So when it drops it would error 'before' the mouse is un-bounded from the slider causing it to stick.

This is a preference thing. Should it ignore any moves less than 2px perhaps?

**Comment by BrechtDeMan** [comment]
I wonder what other interfaces do in cases like this? It just felt a bit unnatural/'cheap' that it couldn't handle my lack of precision when clicking (i.e. not holding perfectly still). 

It could ignore <2px moves like you say; could it then also parse that as a 'click'? (Or even also move it by 2px then, just also toggling playback). 

I admit it's quite a minor thing.

**Comment by nickjillings** [comment]
It's now on a timer. Any mousedown/mouseup events that are under 200ms apart trigger a click. May need to adjust the time a bit, but seems to work well for now.

In Dev_main (0643706)
