### ISSUE TITLE
Lightbox errors heap up / OK button not in focus

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#83]
E.g. If I hit enter on a question without entering text, I get the 'This question is mandatory' error - fair enough. But then I hit enter again to make it disappear, and it doesn't - but instead adds another warning (i.e. the 'Submit' button of the other window is still in focus). 

So 

1. The button of the top window should be in focus
2. Errors should not 'heap up'

See picture:
<img width="720" alt="error-messages" src="https://cloud.githubusercontent.com/assets/4103243/15362779/5282886c-1d0e-11e6-8549-dd3cbc84300e.png">

**Comment by nickjillings** [comment]
The error heap-up is unintentional, the lightbox text is only cleared on its deletion. This will probably be solved also if we define the enter key behaviour in #64
