### ISSUE TITLE
test_create: redundant Interface options menu

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#84]
Why ask the preferred 'Checks' and 'Shows' at the start if they are also part of the general test_create form later? It's confusing and seems to lead to issues.

**Comment by nickjillings** [comment]
Was a way to have them presented perhaps with more information. We could remove it if it is easier?

**Comment by BrechtDeMan** [comment]
I think I would. Also, it is not clear (to me at the very least) how the page interface options inherits from the general interface options, and also for metrics and 'show'. 

Furthermore, some of the 'strikethrough' options can still be modified at a later stage (even when it does not make sense for that interface, e.g. marker position for AB). That said the most important thing is that it doesn't break things if these are (un)checked, but greying out would be nicer. 

Finally, I'm wondering if for something like MUSHRA we should really constrain the options (as is the case right now, at least in the first few pages of the test_create) or just show the defaults and let the user modify what they want.

**Comment by nickjillings** [comment]
Dev_main
