### ISSUE TITLE
test_create: don't include 'gain' unless modified

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#85]
I wanted to set the loudness of a sample (to e.g. -10) but there was also the 'gain' attribute, which is always set to zero. I would guess one takes precedence over the other, and only when the user enters a value in either they should be added to the tag? 

My perception was that the sample was still equally loud despite the different target loudness. 

In AB interface.

**Comment by nickjillings** [comment]
The gain tag == 0.0 if undefined in the specification anyway. The gain tag and loudness tag are two different things. It is possible to normalise all tracks to -10 LUFS and then have a track boosted by 6dB for instance.
