### ISSUE TITLE
Support multiple, customised references

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#93]
I tried to make a MUSHRA-style test with multiple references (see below for XML), but I see that the outside references are then both called ‘reference’, and one is in the middle and the other one appears on the left (see also below). I might want to have the reference at the top of the rating scale, and the 'anchor' i.e. 'poor quality reference' on the bottom (and called ‘anchor’). 

So I believe there should be 

1. a customisable ‘name’ for outside references (with ‘reference’ as the default) - perhaps the ‘name’ attribute could be reused for this - and 
2. a location tag for buttons, perhaps a ‘rating value’. 

For MUSHRA-style, all references could be on the left; for interfaces like AB(X) it could be simply on the top; for APE it could actually be a ‘greyed out’ or different colour slider on the actual axis that cannot be moved - this was the case for the MATLAB APE, which I based off another ancient MATLAB test interface. 

On a similar note, comment boxes are still not created by test_create (#71). 

![MUSHRA screenshot](https://cloud.githubusercontent.com/assets/4103243/15466717/380448a6-20db-11e6-8e95-4c9944810c9f.png)

`<waet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test-schema.xsd"><setup interface="MUSHRA"><exitText>Thank you.</exitText><survey location="pre"></survey><survey location="post"></survey><metric><metricenable>testTimer</metricenable><metricenable>elementTimer</metricenable><metricenable>elementInitialPosition</metricenable><metricenable>elementTracker</metricenable><metricenable>elementFlagListenedTo</metricenable><metricenable>elementFlagMoved</metricenable><metricenable>elementListenTracker</metricenable></metric><interface name="null"></interface></setup><page id="undefined" hostURL="media/example/"><commentboxprefix>Comment on track</commentboxprefix><interface name="null"><title>Quality</title><interfaceoption type="show" name="volume"></interfaceoption><interfaceoption type="show" name="playhead"></interfaceoption><interfaceoption type="show" name="comments"></interfaceoption><interfaceoption type="show" name="page-count"></interfaceoption><scales><scalelabel position="100">Imperceptible</scalelabel><scalelabel position="75">Perceptible but not annoying</scalelabel><scalelabel position="50">Slightly annoying</scalelabel><scalelabel position="25">Annoying</scalelabel><scalelabel position="0">Very annoying</scalelabel></scales></interface><audioelement id="zeroref" url="0.wav" gain="0" name="zero" type="outside-reference"></audioelement><audioelement id="one" url="1.wav" gain="0" name="one"></audioelement><audioelement id="zero" url="0.wav" gain="0" name="zero" type="reference"></audioelement><audioelement id="five" url="5.wav" gain="0" name="five" type="anchor"></audioelement><audioelement id="fiveref" url="5.wav" gain="0" name="five" type="outside-reference"></audioelement><audioelement id="two" url="2.wav" gain="0" name="two"></audioelement><survey location="pre"></survey><survey location="post"></survey></page></waet>`

**Comment by nickjillings** [comment]
I don't think I ever designed it to handle multiple references! Nor is there any outside-anchor type (I didn't think that was MUSHRA). My understanding was MUSHRA had one external and one hidden reference (could be the same) and one hidden anchor.

> a customisable ‘name’ for outside references (with ‘reference’ as the default)
Best to look at the label tag for this

> a location tag for buttons, perhaps a ‘rating value’.
Like the idea but a lot harder to implement. It's easy enough for reference (100) and anchor(0) since we can place them outside the scale, but what about one at 50. Where does that go? To the left/right. Could get messy in this case. For the discrete and horizontal it is easy enough again but for the vertical sliders it is a messy one

**Comment by BrechtDeMan** [comment]
Oh I guess you're right, I was thinking of another test I saw recently which had a '80%' and '20%' reference. 
Changed the title to reflect this.

**Comment by nickjillings** [comment]
All interfaces can now have multiple outside references and are all automatically centered.

I will look at how to change the labels soon, Giulio had done some work in this area

**Comment by nickjillings** [comment]
Implemented now in dev_main. Will pull it forward soon.
