### ISSUE TITLE
popup warning should steal focus from "next" button

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#99]
For instance, if a dialog saying "please enter a valid number" comes up, you should be able to dismiss it by pressing "enter". Currently, pressing enter will cause another  "please enter a valid number" to be stacked in the dialog (because the form is resubmitted), see here 

<img width="679" alt="screen shot 2016-05-24 at 15 48 26" src="https://cloud.githubusercontent.com/assets/4260604/15508391/2943145e-21c7-11e6-9521-edf007e0061d.png">

**Comment by nickjillings** [comment]
Duplicate of #83
